### ISSUE TITLE
Release 2.5.0 broken with VC11

### ISSUE THREAD

**Issue by Jan-E** [m6w6/ext-http#1]
Compiling PHP 5.5.27 with VC11:

	php_http_env_response.c
	ext\http\php_http_env_response.c(232) : error C2143: syntax error : missing ';' before 'type'
	ext\http\php_http_env_response.c(234) : error C2065: 'status' : undeclared identifier
	ext\http\php_http_env_response.c(249) : error C2061: syntax error : identifier 'output'
	ext\http\php_http_env_response.c(249) : error C2059: syntax error : ';'
	ext\http\php_http_env_response.c(249) : error C2059: syntax error : 'type'
	ext\http\php_http_env_response.c(289) : error C2065: 'output' : undeclared identifier
	ext\http\php_http_env_response.c(289) : warning C4047: 'function' : 'php_http_buffer_pass_func_t' differs in levels of indirection from 'int'
	ext\http\php_http_env_response.c(289) : warning C4024: 'php_http_buffer_chunked_output' : different types for formal and actual parameter 5
	ext\http\php_http_env_response.c(292) : error C2065: 'output' : undeclared identifier
	ext\http\php_http_env_response.c(292) : warning C4047: 'function' : 'php_http_buffer_pass_func_t' differs in levels of indirection from 'int'
	ext\http\php_http_env_response.c(292) : warning C4024: 'php_http_buffer_chunked_output' : different types for formal and actual parameter 5
	NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\BIN\cl.
	exe"' : return code '0x2'
	Stop.

Lines 231 and 232 in php_http_env_responce.c should be switched.

**Comment by m6w6** [comment]
Thanks, fixed in b4c6741 -- was already broken in RC1, though.
