### ISSUE TITLE
Call to undefined function http_build_url() 

### ISSUE THREAD

**Issue by akash3456** [m6w6/ext-http#10]
I keep getting this message even though i have installed all necessary dependancies.

**Comment by akash3456** [comment]
so i get the following error message when i try to install a previous version of pecl_http1.7.5:

Makefile:191: recipe for target 'http_message_object.lo' failed
make: *** [http_message_object.lo] Error 1
ERROR: `make' failed

**Comment by remicollet** [comment]
According to your previous post, you are using PHP 5.6.

pecl_http 1.7.x IS NOT compatible with this version.
So definitively, you need to update your application to be compatible with pecl_http 2.x

**Comment by akash3456** [comment]
what version should i install? would appreciate it if you didnt close the issue when it hasnt been resolved.

**Comment by remicollet** [comment]
I close this, as this is NOT an pecl_http issue.

pecl_http version 1.x  is compatible with php <= 5.5
pecl_http version 2.x  is compatible with php >= 5.3

**Comment by akash3456** [comment]
You have just said that http2.x does not work with php 5.6 in the previous post.

**Comment by akash3456** [comment]
my version was 2.0 to start with and i got the undefined function error in the browser.

**Comment by remicollet** [comment]
> You have just said that http2.x does not work with php 5.6 in the previous post.

Please read it again.

> my version was 2.0 to start with and i got the undefined function error in the browser.

Yes, because the API have change between 1.x and 2.x
So definitively, your code expect v1. So you need to fix your code.

**Comment by akash3456** [comment]
i have just installed 1.0.0 and i get this again : 
Makefile:191: recipe for target 'http_message_object.lo' failed
make: *** [http_message_object.lo] Error 1
ERROR: `make' failed

**Comment by remicollet** [comment]
Sorry I don't how how to explain it more clearly  "pecl_http 1..x IS NOT compatible with PHP version 5.6".

I give up.

**Comment by akash3456** [comment]
WHEN I HAVE INSTALLED V2.5.1 I GET A UNDEFINED FUNCTION ERROR IN THE BROWSER WHICH MEANS I DID WHAT YOU SAID.

**Comment by akash3456** [comment]
WHERE CAN I GET ACCESS TO THE FULL API DOCUMENTATION FOR V2.0

**Comment by akash3456** [comment]
when i changed the code to use the v2 API i still get: Class 'http\Client\Request' not found .
