### ISSUE TITLE
Propose: New release RELEASE_3_2_4_RC1: including php7.4 changes

### ISSUE THREAD

**Issue by mmokhi** [m6w6/ext-http#104]
I would like to propose new release (or at least RC), I think [php7.4 test fixes](https://github.com/m6w6/ext-http/compare/RELEASE_3_2_3...master) are worth having a new release :slightly_smiling_face:  (or getting them included in the previous release-tag :slightly_smiling_face: )

**Comment by m6w6** [comment]
Maybe. There's a upstream fix oming though: https://github.com/php/php-src/commit/e87dc32569c1c5e11683d9e878da3fddd0409c40

**Comment by Jan-E** [comment]
Fixed with https://github.com/m6w6/ext-http/commit/58c532fe1d2a27b50d49197b5eb77b85cdf03dfb
