### ISSUE TITLE
Build failure `fatal error: 'ext/raphf/php_raphf_api.h' file not found`

### ISSUE THREAD

**Issue by Synchro** [m6w6/ext-http#105]
I have raphf installed from pecl, but attempting to install pecl_http, also from pecl, is failing like this:

```
In file included from /private/tmp/pear/temp/pecl_http/src/php_http.c:13:
/private/tmp/pear/temp/pecl_http/src/php_http_api.h:34:10: fatal error: 'ext/raphf/php_raphf_api.h' file not found
#include "ext/raphf/php_raphf_api.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [src/php_http.lo] Error 1
ERROR: `make' failed
```

Even though I have raphf installed, I can't see the `ext/raphf/php_raphf_api.h` file anywhere in my installation, so I'm wondering how it's supposed to be installed for pecl_http to install.

I made it work by manually download this file and `ext/raphf/php_raphf.h` from the raphf project repo and put them in `/usr/local/Cellar/php/7.4.3/include/php/ext/raphf/`, but that seems fragile and doesn't seem like something I should need to do?

**Comment by m6w6** [comment]
Make sure you're using GNU make, see https://github.com/m6w6/ext-raphf/issues/4
