### ISSUE TITLE
pecl install pecl_http error  on mac  OS catalina

### ISSUE THREAD

**Issue by bennami** [m6w6/ext-http#106]
when i try to install this  package  i get  an error.  i am guessing it has  something  to  do  with the  fact that  mac OS installs some  packages in a different path  file. i  am not sure as to what i should do to fix this.

`imanes-MacBook-Pro:begame imane$ pecl install pecl-http
parsePackageName(): "http" is neither a valid version nor a valid state in "pecl-http"
invalid package name/package file "pecl-http"
install failed
imanes-MacBook-Pro:begame imane$ pecl install pecl_http
downloading pecl_http-3.2.3.tgz ...
Starting to download pecl_http-3.2.3.tgz (220,204 bytes)
..............................................done: 220,204 bytes
84 source files, building
running: phpize
Configuring for:
PHP Api Version:         20180731
Zend Module Api No:      20180731
Zend Extension Api No:   320180731
where to find zlib [/usr] : 

Warning: Use of undefined constant name - assumed 'name' (this will throw an Error in a future version of PHP) in Builder.php on line 407
PHP Warning:  Use of undefined constant name - assumed 'name' (this will throw an Error in a future version of PHP) in /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Builder.php on line 407
PHP Stack trace:
PHP   1. {main}() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/peclcmd.php:0
PHP   2. require_once() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/peclcmd.php:32
PHP   3. PEAR_Command_Install->run() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/pearcmd.php:317
PHP   4. PEAR_Command_Install->doInstall() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Command/Common.php:270
PHP   5. PEAR_Installer->install() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Command/Install.php:718
PHP   6. PEAR_Installer->_compileSourceFiles() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Installer.php:1416
PHP   7. PEAR_Builder->build() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Installer.php:1521
where to find libcurl [/usr] : 

Warning: Use of undefined constant name - assumed 'name' (this will throw an Error in a future version of PHP) in Builder.php on line 407
PHP Warning:  Use of undefined constant name - assumed 'name' (this will throw an Error in a future version of PHP) in /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Builder.php on line 407
PHP Stack trace:
PHP   1. {main}() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/peclcmd.php:0
PHP   2. require_once() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/peclcmd.php:32
PHP   3. PEAR_Command_Install->run() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/pearcmd.php:317
PHP   4. PEAR_Command_Install->doInstall() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Command/Common.php:270
PHP   5. PEAR_Installer->install() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Command/Install.php:718
PHP   6. PEAR_Installer->_compileSourceFiles() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Installer.php:1416
PHP   7. PEAR_Builder->build() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Installer.php:1521
where to find libevent [/usr] : 

Warning: Use of undefined constant name - assumed 'name' (this will throw an Error in a future version of PHP) in Builder.php on line 407
PHP Warning:  Use of undefined constant name - assumed 'name' (this will throw an Error in a future version of PHP) in /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Builder.php on line 407
PHP Stack trace:
PHP   1. {main}() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/peclcmd.php:0
PHP   2. require_once() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/peclcmd.php:32
PHP   3. PEAR_Command_Install->run() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/pearcmd.php:317
PHP   4. PEAR_Command_Install->doInstall() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Command/Common.php:270
PHP   5. PEAR_Installer->install() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Command/Install.php:718
PHP   6. PEAR_Installer->_compileSourceFiles() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Installer.php:1416
PHP   7. PEAR_Builder->build() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Installer.php:1521
where to find libicu [/usr] : 

Warning: Use of undefined constant name - assumed 'name' (this will throw an Error in a future version of PHP) in Builder.php on line 407
PHP Warning:  Use of undefined constant name - assumed 'name' (this will throw an Error in a future version of PHP) in /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Builder.php on line 407
PHP Stack trace:
PHP   1. {main}() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/peclcmd.php:0
PHP   2. require_once() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/peclcmd.php:32
PHP   3. PEAR_Command_Install->run() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/pearcmd.php:317
PHP   4. PEAR_Command_Install->doInstall() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Command/Common.php:270
PHP   5. PEAR_Installer->install() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Command/Install.php:718
PHP   6. PEAR_Installer->_compileSourceFiles() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Installer.php:1416
PHP   7. PEAR_Builder->build() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Installer.php:1521
where to find libidn2 [/usr] : 

Warning: Use of undefined constant name - assumed 'name' (this will throw an Error in a future version of PHP) in Builder.php on line 407
PHP Warning:  Use of undefined constant name - assumed 'name' (this will throw an Error in a future version of PHP) in /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Builder.php on line 407
PHP Stack trace:
PHP   1. {main}() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/peclcmd.php:0
PHP   2. require_once() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/peclcmd.php:32
PHP   3. PEAR_Command_Install->run() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/pearcmd.php:317
PHP   4. PEAR_Command_Install->doInstall() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Command/Common.php:270
PHP   5. PEAR_Installer->install() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Command/Install.php:718
PHP   6. PEAR_Installer->_compileSourceFiles() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Installer.php:1416
PHP   7. PEAR_Builder->build() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Installer.php:1521
where to find libidn [/usr] : 

Warning: Use of undefined constant name - assumed 'name' (this will throw an Error in a future version of PHP) in Builder.php on line 407
PHP Warning:  Use of undefined constant name - assumed 'name' (this will throw an Error in a future version of PHP) in /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Builder.php on line 407
PHP Stack trace:
PHP   1. {main}() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/peclcmd.php:0
PHP   2. require_once() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/peclcmd.php:32
PHP   3. PEAR_Command_Install->run() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/pearcmd.php:317
PHP   4. PEAR_Command_Install->doInstall() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Command/Common.php:270
PHP   5. PEAR_Installer->install() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Command/Install.php:718
PHP   6. PEAR_Installer->_compileSourceFiles() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Installer.php:1416
PHP   7. PEAR_Builder->build() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Installer.php:1521
where to find libidnkit2 [/usr] : 

Warning: Use of undefined constant name - assumed 'name' (this will throw an Error in a future version of PHP) in Builder.php on line 407
PHP Warning:  Use of undefined constant name - assumed 'name' (this will throw an Error in a future version of PHP) in /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Builder.php on line 407
PHP Stack trace:
PHP   1. {main}() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/peclcmd.php:0
PHP   2. require_once() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/peclcmd.php:32
PHP   3. PEAR_Command_Install->run() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/pearcmd.php:317
PHP   4. PEAR_Command_Install->doInstall() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Command/Common.php:270
PHP   5. PEAR_Installer->install() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Command/Install.php:718
PHP   6. PEAR_Installer->_compileSourceFiles() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Installer.php:1416
PHP   7. PEAR_Builder->build() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Installer.php:1521
where to find libidnkit [/usr] : 

Warning: Use of undefined constant name - assumed 'name' (this will throw an Error in a future version of PHP) in Builder.php on line 407
PHP Warning:  Use of undefined constant name - assumed 'name' (this will throw an Error in a future version of PHP) in /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Builder.php on line 407
PHP Stack trace:
PHP   1. {main}() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/peclcmd.php:0
PHP   2. require_once() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/peclcmd.php:32
PHP   3. PEAR_Command_Install->run() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/pearcmd.php:317
PHP   4. PEAR_Command_Install->doInstall() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Command/Common.php:270
PHP   5. PEAR_Installer->install() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Command/Install.php:718
PHP   6. PEAR_Installer->_compileSourceFiles() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Installer.php:1416
PHP   7. PEAR_Builder->build() /usr/local/Cellar/php@7.3/7.3.14/share/php@7.3/pear/PEAR/Installer.php:1521
building in /private/tmp/pear/temp/pear-build-imanen5Rlox/pecl_http-3.2.3
running: /private/tmp/pear/temp/pecl_http/configure --with-php-config=/usr/local/opt/php@7.3/bin/php-config --with-http-zlib-dir=/usr --with-http-libcurl-dir=/usr --with-http-libevent-dir=/usr --with-http-libicu-dir=/usr --with-http-libidn2-dir=/usr --with-http-libidn-dir=/usr --with-http-libidnkit2-dir=/usr --with-http-libidnkit-dir=/usr

checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-apple-darwin19.3.0
checking host system type... x86_64-apple-darwin19.3.0
checking target system type... x86_64-apple-darwin19.3.0
checking for PHP prefix... /usr/local/Cellar/php@7.3/7.3.14
checking for PHP includes... -I/usr/local/Cellar/php@7.3/7.3.14/include/php -I/usr/local/Cellar/php@7.3/7.3.14/include/php/main -I/usr/local/Cellar/php@7.3/7.3.14/include/php/TSRM -I/usr/local/Cellar/php@7.3/7.3.14/include/php/Zend -I/usr/local/Cellar/php@7.3/7.3.14/include/php/ext -I/usr/local/Cellar/php@7.3/7.3.14/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/Cellar/php@7.3/7.3.14/pecl/20180731
checking for PHP installed headers prefix... /usr/local/Cellar/php@7.3/7.3.14/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable extended HTTP support... yes, shared
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for off_t... yes
checking for mbstate_t... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking for unistd.h... (cached) yes
checking wchar.h usability... yes
checking wchar.h presence... yes
checking for wchar.h... yes
checking wctype.h usability... yes
checking wctype.h presence... yes
checking for wctype.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking for gethostname... yes
checking for getdomainname... yes
checking for mbrtowc... yes
checking for mbtowc... yes
checking for iswalnum... yes
checking for inet_pton... yes
checking whether/where to check for zlib... /usr
checking for gawk... (cached) awk
checking for zlib... no
checking whether zlib version  >= 1.2.0.4... configure: error: no
ERROR: `/private/tmp/pear/temp/pecl_http/configure --with-php-config=/usr/local/opt/php@7.3/bin/php-config --with-http-zlib-dir=/usr --with-http-libcurl-dir=/usr --with-http-libevent-dir=/usr --with-http-libicu-dir=/usr --with-http-libidn2-dir=/usr --with-http-libidn-dir=/usr --with-http-libidnkit2-dir=/usr --with-http-libidnkit-dir=/usr' failed

`

**Comment by m6w6** [comment]
You need to provide the real path to zlib, then, which the installer already asks for.

HTH.

**Comment by bennami** [comment]
how do i do that?

**Comment by bennami** [comment]
i tried installing zlib via brew but i  get this  warning:

`For compilers to find zlib you may need to set:
  export LDFLAGS="-L/usr/local/opt/zlib/lib"
  export CPPFLAGS="-I/usr/local/opt/zlib/include"`

i dont know what to do with this.  i understand that i need to  change the path somewhere so it knows to find the packages

**Comment by bennami** [comment]
solution: [here](https://stackoverflow.com/questions/60954664/compooser-update-cannot-run-because-ext-http-extension-missing-from-my-system-ma/60958958#60958958)

**Comment by nathanael-anstett** [comment]
> solution: [here](https://stackoverflow.com/questions/60954664/compooser-update-cannot-run-because-ext-http-extension-missing-from-my-system-ma/60958958#60958958)

Dead link

**Comment by Synchro** [comment]
The solution that page recommended is to give `/usr/local/opt/zlib` as the path to zlib.

**Comment by Synchro** [comment]
For the searchers, in a similar theme, if you encounter this compile error when using homebrew:

    fatal error: 'unicode/uversion.h' file not found

Provide the path to libicu when you're asked:

    where to find libicu [/usr] :  /usr/local/opt/icu4c

**Comment by Synchro** [comment]
So here I am, finding my own error reports again...

Since macOS Monterey, homebrew has moved to `/opt/homebrew`, so the paths in my earlier comments need to be updated to `/opt/homebrew/opt/zlib` and `/opt/homebrew/opt/icu4c`.
