### ISSUE TITLE
Git merge conflict in the source code

### ISSUE THREAD

**Issue by designermonkey** [m6w6/ext-http#107]
https://github.com/m6w6/ext-http/blob/b4cde84693954dba769907858199f3e1dee947b4/src/php_http_header.c#L52

There's a merge conflict statement in the codebase.

**Comment by m6w6** [comment]
Duh, now that was quite startling. But it's just in a comment.

**Comment by designermonkey** [comment]
Oh yeah I see :) Okidoke.
