### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by grosjo** [m6w6/ext-http#108]
Hello

With latest git

- On PHP 7.3.x:
/data/src/pecl/ext-http/src/php_http_client.c:1095:70: error: ‘ZEND_THIS’ undeclared (first use in this function); did you mean ‘ZEND_TLS’?
 1095 |  observers = zend_read_property(php_http_client_class_entry, Z_OBJ_P(ZEND_THIS), ZEND_STRL("observers"), 0, &observers_tmp);

- On PHP 7.4.x:
/data/src/pecl/ext-http/src/php_http_etag.c:24:28: error: too few arguments to function ‘php_hash_fetch_ops’
   24 |  const php_hash_ops *eho = php_hash_fetch_ops(mode_str);

**Comment by m6w6** [comment]
Sorry, v4 (master) is PHP-8 only. For PHP-7, go for the v3.x branch.
