### ISSUE TITLE
PHP 8.0 - Windows 10 x64 - Unable to load dynamic library 'http'

### ISSUE THREAD

**Issue by ybenhssaien** [m6w6/ext-http#111]
# Description
Hi, on some reason my php cannot load `php_http.dll` module 

# Issue
1. Install `PHP 8.0.2 (cli) (built: Feb  3 2021 18:36:37) ( NTS Visual C++ 2019 x64 )` on Windows 10 x64
2. Download the version 4.0 from
2. Place it in the `ext` dir : `C:\bin\php\php-8.0.2-nts-Win32-vs16-x64\ext\php_http.dll`
3. execute `php -v`

![image](https://user-images.githubusercontent.com/7301643/115142694-60aaee80-a043-11eb-91f4-e5d16af6363c.png)

# Technical specifications
* Windows 10 Pro x64
* PHP 8.0.* Non Thread Safe x64 : https://windows.php.net/download/#php-8.0-nts-vs16-x64
* pecl_http 4.0 : https://windows.php.net/downloads/pecl/releases/pecl_http/4.0.0/php_pecl_http-4.0.0-8.0-nts-vs16-x64.zip

**Comment by m6w6** [comment]
Actually, I have no idea, sorry :shrug: 

Does the `extension` line look like the other `extension` lines in `php.ini` and did you also add the required `raphf` extension?
