### ISSUE TITLE
PHP 8.1: Implement __serialize() and __unserialize()

### ISSUE THREAD

**Issue by Jan-E** [m6w6/ext-http#115]
The extension builds fine with PHP 8.1 (Windows, VS16) but issues several warnings when running the tests:
 > Deprecated: The Serializable interface is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary)

When I ran the tests and suppressed E_DEPRECATED the results were the same as under PHP 8,.0, except for the test that explicitely tested for client deprecated methods:
https://github.com/m6w6/ext-http/blob/master/tests/client024.phpt

This test succeeded under PHP 8.0, but failed under PHP 8.1.

**Comment by Jan-E** [comment]
I know of only one PHP extension that implements the `Serializable interface` as well as `__serialize() and __unserialize()`: igbinary. But even in that extension it seems difficult to implement: See
https://github.com/igbinary/igbinary/commit/ddc68d59cdd784f538942f650c3e8d84a1db10ff

I am too unexperienced with Classes in C to give it a shot myself. Anyone else?

**Comment by remicollet** [comment]
See pr #114 (wip)

**Comment by Jan-E** [comment]
Ok. I did not see that you were already working on it.
