### ISSUE TITLE
HTTPS does not seem to work on Windows?

### ISSUE THREAD

**Issue by optyfr** [m6w6/ext-http#122]
I get 

```
http\Exception\RuntimeException: http\Client::send(): SSL peer certificate or SSH remote key was not OK; SSL certificate problem: unable to get local issuer certificate (https://test.compodata.eu/) in D:\Referentiel\LSReferentielPreProd\test2.php:6
Stack trace:
#0 D:\Referentiel\LSReferentielPreProd\test2.php(6): http\Client->send()
#1 {main}
```
The code is
```
try {
	$client = new \http\Client();
	$client->setSslOptions(['cainfo'=>'c:\php\extras\ssl\cacert.pem',"verifypeer"=>false]);
	$client->enqueue(new \http\Client\Request("GET", "https://test.compodata.eu"));
	$client->send();
	echo "pecl_http success :<br>";
} catch (Exception $e) {
	echo "pecl_http FAIL :<pre>$e</pre>";
}

```

It does not seem to take into account SSL options, the line setSSLOptions does nothing, and setOptions is not better
I tried using PHP 8.0 NTS x64 using 4.2.0 and 4.0.0 without success (4.1.0 did not load)
I tried using PHP 7.4 NTS x64 using 3.2.4 and 3.2.3 but the extension did not load at all (with no error using php -m)

by the way I directly tried the same site using curl extension and an initialized cainfo, and it worked fine on the same server/php

did I miss something?

**Comment by optyfr** [comment]
btw this is not specific to my test site, the same thing happen for www.google.com

**Comment by cmb69** [comment]
I triggered new builds of PECL/http 3.2.4 and these are using the proper ICU, but they still don't load. I'll have a closer look on Monday.

**Comment by Jan-E** [comment]
Possibly related:
https://stackoverflow.com/questions/61650504/use-of-undefined-constant-curlopt-tcp-fastopen

**Comment by Jan-E** [comment]
https://github.com/curl/curl/blob/823d3ab855c55e26d595cfda1a13814baa0f684c/docs/TODO#L389-L393

    1.24 TCP Fast Open for windows
    
     libcurl supports the CURLOPT_TCP_FASTOPEN option since 7.49.0 for Linux and
     Mac OS. Windows supports TCP Fast Open starting with Windows 10, version 1607
     and we should add support for it.

**Comment by m6w6** [comment]
Hi all! I guess this can be closed? Please re-open if I was missing something. Thanks!
