### ISSUE TITLE
Cookie tests fail for 3.2.5 on CentOS 7 with custom-built php/curl

### ISSUE THREAD

**Issue by pprkut** [m6w6/ext-http#125]
Hi!

I'm building my own php and curl on top of CentOS 7 and in the past this always worked quite fine. Now, however, I'm getting test failures that I'm not sure how to sort :-/

I have php 7.4.29 and curl 7.83.1, built against libpsl 0.21.1. I had to update libpsl because one of curl's own tests would fail with the libpsl from epel (0.7.0), but the test failures I see for pecl_http also happen with the older libpsl (and curl 7.82.0) so that might not be it.

I'm seeing these failures:
```
TEST 31/204 [tests/client021.phpt]
========DIFF========
002+ # reusing curl handles
003+ Expected counter=2, got 1
004+ # reusing curl handles
005+ Expected counter=3, got 1
========DONE========
FAIL client cookies [tests/client021.phpt]

TEST 37/204 [tests/client027.phpt]
========DIFF========
007+ Set-Cookie: counter=1;
007- Set-Cookie: counter=2;
011+ Set-Cookie: counter=1;
011- Set-Cookie: counter=2;
========DONE========
FAIL client cookie woes [tests/client027.phpt]

TEST 41/204 [tests/client031.phpt]
========DIFF========
011+ Set-Cookie: counter=1;
011- Set-Cookie: counter=2;
========DONE========
FAIL client cookie sharing disabled [tests/client031.phpt]

TEST 42/204 [tests/client032.phpt]
========DIFF========
007+ Set-Cookie: counter=1;
007- Set-Cookie: counter=2;
011+ Set-Cookie: counter=1;
011- Set-Cookie: counter=2;
015+ Set-Cookie: counter=1;
015- Set-Cookie: counter=3;
019+ Set-Cookie: counter=1;
019- Set-Cookie: counter=4;
========DONE========
FAIL client cookie sharing enabled [tests/client032.phpt]
```
It's entirely possible this is a problem on my end, but I'm not sure where to start looking. If you have some pointers for me that would be great :)

**Comment by m6w6** [comment]
Hi, thanks for your report!

Please have a try with the just updated [v3.x branch](https://github.com/m6w6/ext-http/tree/v3.x).

**Comment by pprkut** [comment]
@m6w6 Works! :partying_face: 
Thank you! :slightly_smiling_face:

**Comment by m6w6** [comment]
Release has been pushed!
