### ISSUE TITLE
Windows; extension loaded but offers no functions?

### ISSUE THREAD

**Issue by kimboslice99** [m6w6/ext-http#128]
System info:
- Windows Server 2019 17763
- PHP v8.1.16
 
Seems even after loading the extension, and it appearing under `phpinfo()` and `php -m`, none of the functions appear with `print_r(get_extension_funcs("http"))`

The dependencies are present... raphf, iconv, and hash are all loaded before php_http.dll

Unsure what to do? No errors present anywhere

**Comment by m6w6** [comment]
This extension does not provide any plain functions, see its [documentation](https://mdref.m6w6.name/http#Namespaces.Interfaces.and.Classes:).

**Comment by kimboslice99** [comment]
Thanks for the response, ya I have read through that and didn't make much of any progress, ah well, suppose I'll come back to this when I've learned more

**Comment by m6w6** [comment]
Depending on what you want to do, have a start [with](https://mdref.m6w6.name/http/Env/Response/__construct#Example:) - [some](https://mdref.m6w6.name/http/Message/Body/addForm#Example:) - [examples](https://mdref.m6w6.name/http/Client/:%20Examples), I guess.

**Comment by kimboslice99** [comment]
Suppose I may have been reading old docs or something that had pointed me to this extension for a few functions to serve files, like http_send_file, but it would seem this is moved to the http\Env\Response class

However I see its noted 
```
If you need throttling by regular means, check for other options in your stack, because this method blocks the executing process/thread until the response has completely been sent.
```

So I guess this isn't really a great solution for serving large files?

**Comment by m6w6** [comment]
Just don't use  `STDOUT` at all, when you're not on the CLI.
