### ISSUE TITLE
.ddl for php 8.2 ?

### ISSUE THREAD

**Issue by ErnadoO** [m6w6/ext-http#130]
Hi

I would like to know if there are any plan to build this extension for php 8.2 on windows ?

I was able to compile php_raphf.dll with this [tutorial](https://medium.com/@erinus/how-to-build-php-extension-on-windows-d1667290f809) but i still get an error when i try with http.

Thanks :)

**Comment by m6w6** [comment]
Hi! Sorry, I've no idea what the PHP-Windows folks are up to nowadays. IIRC their build machine crashed and they haven't been sponsored a new one.

**Comment by ErnadoO** [comment]
Hi @m6w6 thanks for answer.

After many many attemps, i succeeded compile this ext for php 8.2 for windows (Wamp 64 bits with PHP 8.2.5)

I share my work, I hope it will be useful to others in the same situation:

[php_http.zip](https://github.com/m6w6/ext-http/files/11496391/php_http.zip)
