### ISSUE TITLE
Error using ssl array in options : Could not set option tlsauthtype (An unknown option was passed in to libcurl)

### ISSUE THREAD

**Issue by pugelarouge** [m6w6/ext-http#131]
I have an issue as of versions in ubuntu 23.04, was OK in 22.10 (also have the issue on gentoo - slightly different combinations of versions)

this may relate to d758be5353448f9a72764198a6bf9d86b09daa2a not sure - I am running from pre-compiled packages

With my current version if I pass the ssl array in options I now get the error : **Error using ssl array in options : Could not set option tlsauthtype (An unknown option was passed in to libcurl)**

I'm not sure if this is a bug in pecl_http or libcurl or maybe openssl ?
either way I am looking for a way to be able to still pass ssl options so a workaround would be useful in the short term (setting tlsauthtype in options ?)

If this is not a problem here please point me in the correct direction to report it (upstream package ?)

example code to trigger issue below

```
<?php
/* test ssl options for libcurl via pecl_http (v4.x)

works with ubuntu 22.10 [amd64]
		php-http 4.2.3-1build1
		libcurl4 7.85.0-1ubuntu0.5
		curl 7.85.0-1ubuntu0.5
		libcurl3-gnutls 7.85.0-1ubuntu0.5
		libgnutls-openssl27 3.7.7-2ubuntu2.1
		openssl 3.0.5-2ubuntu2.3
		php8.1-curl 8.1.7-1ubuntu3.5
		php8.1 8.1.7-1ubuntu3.5

error with ubuntu 23.04 [amd64]
		php-http 4.2.3-3.1ubuntu1
		libcurl4 7.88.1-8ubuntu2.1
		curl 7.88.1-8ubuntu2.1
		libcurl3-gnutls 7.88.1-8ubuntu2.1
		libgnutls-openssl27 3.7.8-5ubuntu1
		openssl 3.0.8-1ubuntu1.2
		php8.1-curl 8.1.12-1ubuntu4.3
		php8.1 8.1.12-1ubuntu4.3
		
error with gentoo
		dev-php/pecl-http-4.2.2:8
		net-misc/curl-8.0.1
		dev-libs/openssl-3.0.9-r2
		dev-lang/php-8.1.16
*/

// target / opts - see https://mdref.m6w6.name/http/Client/Curl

// related to ? https://github.com/m6w6/ext-http/commit/d758be5353448f9a72764198a6bf9d86b09daa2a#diff-1dc6950f5ad89be41c260211f8135ffb3f8c82e07798d9f9bae61b1e9b30ae34
// see generic https issue here
$https_url = "https://www.google.com/";
$opts = [
		'timeout' => 60
		, 'dns_cache_timeout' => 50
		, 'connecttimeout' => 10
		, 'useragent' => 'MyTestApp'
		, 'ssl' => [ 'verifypeer' => FALSE , 'verifyhost' => FALSE ]
	];

// prep pecl_http request / options / client
$request = new \http\Client\Request('GET', $https_url);
$request->setHeader('Content-Length', 0);
$request->setOptions($opts);
$client = new \http\Client;

try {
	$client->enqueue($request); // POP : Could not set option tlsauthtype (An unknown option was passed in to libcurl)
	$client->send();
	$response = $client->getResponse();
} catch (\Exception $e) {
	die('request failed : '.$e->getMessage()."\n\n");
}

if( ! empty($response) ) {
	$returned = [];
	$returned['body'] = $response->getBody()->toString();
	$returned['headers'] = $response->getHeaders();
	$returned['responseCode'] = $response->getResponseCode();
	print_r($returned);
}
else {
	die('$response was empty ! (null/false/zero/blah)');
}
```

**Comment by pugelarouge** [comment]
Any chance of an update on this (even if just to say it works fine for everyone else an dI have screwed my install/code) - I realise that this is probably due to a change in behaviour of libcurl between versions 7.85 and 7.88 or possibly openSSL between 3.0.5 and 3.0.8 as in all cases is pecl_http 4.2.3, but I am presuming pecl_http needs a change to match this new behaviour

**Comment by m6w6** [comment]
Looks like the bug has already been fixed in master; any chance you could try that?
If, then all we're missing is just a release!

**Comment by m6w6** [comment]
No worries, I'm currently checking myself!

**Comment by m6w6** [comment]
v4.2.4 has just been released!

Thank you!

**Comment by pugelarouge** [comment]
OK - I still am having issues on ubuntu (having got http.so to build) - will test on gentoo / try your 4.2.4 release

**Comment by m6w6** [comment]
Ubuntu ships pecl_http nowadays?

**Comment by pugelarouge** [comment]
Yep - as php-http : https://packages.ubuntu.com/lunar/php-http
I'll try and work out how to raise a bug / request a version bump
