### ISSUE TITLE
Potential compilation error with PHP 8.4 

### ISSUE THREAD

**Issue by HeenaBansal20** [m6w6/ext-http#137]
pecl_http throws below  error with PHP 8.4 alpha2 .

/tmp/pear/temp/pecl_http/src/php_http_message_body.c:15:10: fatal error: ext/standard/php_lcg.h: No such file or directory
    | #include "ext/standard/php_lcg.h"
     |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
 make: *** [Makefile:293: src/php_http_message_body.lo] Error 1
 ERROR: `make' failed

**Comment by m6w6** [comment]
Fixed in 62d6ead5b2baa151bc3cdd158a85677ff3ba4e5e

**Comment by HeenaBansal20** [comment]
Thanks @m6w6 for the quick fix. I see that fix is available in master . Would it be possible for you release it so that I can use the fix for my application to compile with http extension.

**Comment by HeenaBansal20** [comment]
@m6w6 , Any ETA when the new version from master branch would be available to use publicly.

**Comment by m6w6** [comment]
Well, there are still the looming crashes with curl >= 8.9 
https://github.com/m6w6/ext-http/actions/runs/11019460899

**Comment by HeenaBansal20** [comment]
@m6w6 , I am looking for the fix to be released.  We have RC3 out for pHP 8.4. 
Any ETA when this fix will be released.

**Comment by HeenaBansal20** [comment]
@m6w6 , I see that 4.2.6 was released 2 weeks before but pecl didn't list 4.2.6 yet.  
Any reason ?

**Comment by m6w6** [comment]
What the heck. I was sick those days, but oh well, it must have been some delirium... Fixed, thanks, and sorry!
