### ISSUE TITLE
URL's with underscore in the domain name

### ISSUE THREAD

**Issue by pyscht** [m6w6/ext-http#14]
Trying to set URL like ```https://foo_bar-bucket.s3.amazonaws.com``` causes an error: ```http\Message::setRequestUrl(): Failed to parse IDN; ICU error 66563```.

While ```cURL``` works correctly with such domain names.

**Comment by m6w6** [comment]
http\Url currently adheres to [STD3_ASCII_RULES](https://www.rfc-editor.org/std/std3.txt) when parsing IDN (with the help of either libidn, libidn2 or ICU); i.e. [a-zA-Z0-9-].

When using http\Message::setRequestUrl() with a string, http\Url will internally enable all flags, i.e. including [http\Url::PARSE_TOIDN](https://mdref.m6w6.name/http/Url#PARSE_TOIDN); if you explicitly do not need IDNA, you can pass an instance of http\Url to http\Message::setRequestUrl(), like:

    $msg->setRequestUrl(new http\Url("https://foo_bar-bucket.s3.amazonaws.com", null, 0));

**Comment by m6w6** [comment]
BTW, are these hostnames assigned by amazon or is this a user-choice?

**Comment by DicsyDel** [comment]
Amazon doesn't allow users to create buckets with "_", but in some cases they auto-generating billing bucket names with underscore. Maybe just a bug on their end.

**Comment by m6w6** [comment]
Haha, glorious :)
