### ISSUE TITLE
PHP7 status on Windows (VC14)

### ISSUE THREAD

**Issue by Jan-E** [m6w6/ext-http#15]
@m6w6 Hi Mike,

What is the status of propro, raphf and http on Windows (VC14)? I got it to compile, but had to make some changes. See my forks at https://github.com/Jan-E/repositories

Building wit cUrl support failed with these errormessages:

	ext\http\src/php_http_client_curl.c(2181): error C2039: 'client': is not a member of '_zend_php_http_globals'
	ext\http\src/php_http_client_curl.c(2181): error C2198: 'php_persistent_handle_concede': too few arguments for call
	ext\http\src/php_http_client_curl.c(2501): error C2039: 'client': is not a member of '_zend_php_http_globals'
	ext\http\src/php_http_client_curl.c(2502): error C2039: 'client': is not a member of '_zend_php_http_globals'
	ext\http\src/php_http_client_curl.c(2503): error C2039: 'client': is not a member of '_zend_php_http_globals'
	ext\http\src/php_http_client_curl.c(2504): error C2039: 'client': is not a member of '_zend_php_http_globals'
	ext\http\src/php_http_client_curl.c(2506): error C2039: 'client': is not a member of '_zend_php_http_globals'
	ext\http\src/php_http_client_curl.c(2506): error C2198: 'php_http_client_driver_add': too few arguments for call
	ext\http\src/php_http_client_curl.c(2510): error C2039: 'client': is not a member of '_zend_php_http_globals'
	ext\http\src/php_http_client_curl.c(2510): error C2198: 'php_persistent_handle_provide': too few arguments for call
	ext\http\src/php_http_client_curl.c(2513): error C2039: 'client': is not a member of '_zend_php_http_globals'
	ext\http\src/php_http_client_curl.c(2513): error C2198: 'php_persistent_handle_provide': too few arguments for call
	ext\http\src/php_http_client_curl.c(2607): error C2039: 'client': is not a member of '_zend_php_http_globals'
	ext\http\src/php_http_client_curl.c(2607): error C2198: 'php_persistent_handle_cleanup': too few arguments for call
	ext\http\src/php_http_client_curl.c(2608): error C2039: 'client': is not a member of '_zend_php_http_globals'
	ext\http\src/php_http_client_curl.c(2608): error C2198: 'php_persistent_handle_cleanup': too few arguments for call
	ext\http\src/php_http_client_curl.c(2609): error C2039: 'client': is not a member of '_zend_php_http_globals'
	ext\http\src/php_http_client_curl.c(2609): error C2198: 'zend_string_release': too few arguments for call
	ext\http\src/php_http_client_curl.c(2610): error C2039: 'client': is not a member of '_zend_php_http_globals'
	ext\http\src/php_http_client_curl.c(2610): error C2198: 'zend_string_release': too few arguments for call
	ext\http\src/php_http_client_curl.c(2611): error C2039: 'client': is not a member of '_zend_php_http_globals'
	ext\http\src/php_http_client_curl.c(2611): error C2198: 'zend_string_release': too few arguments for call

**Comment by m6w6** [comment]
Hi Jan! Generally, they should work. The config.w32 might be quite broken though. Looks like the right AC_DEFINE()'s are missing. Important is, tough, that only master or release branches are working together, and not e.g. one ext from master and one ext from R_*.

**Comment by Jan-E** [comment]
If I use the 3 extensions from master, the configure fails with

	C:\php-sdk\php70dev\configure.js(1443, 2) Microsoft JScript runtime error: Object doesn't support this property or method

I had to revert the config.w32's to more or less the previous state. The configure seems to stumble over the for loop with copy_and_subst.

With reverted config.w32's, the Windows build script seems to expect at least one *.c file in the root of the extension. Otherwise the linking at the end fails. I solved this by adding an empty php_propro.c in the root: https://github.com/Jan-E/ext-propro/commit/c5335b939463f059cc184fbac89926920579d2d5

And even with working config.w32's the cUrl support is broken. See the errors in the first message above.

Complete listing while building from master:

	C:\php-sdk\php70dev\ext>git clone https://github.com/m6w6/ext-http http
	Cloning into 'http'...
	remote: Counting objects: 12537, done.
	remote: Total 12537 (delta 0), reused 0 (delta 0), pack-reused 12537
	Receiving objects: 100% (12537/12537), 3.00 MiB | 484.00 KiB/s, done.
	Resolving deltas: 100% (9278/9278), done.
	Checking connectivity... done.
	
	C:\php-sdk\php70dev\ext>git clone https://github.com/m6w6/ext-raphf raphf
	Cloning into 'raphf'...
	remote: Counting objects: 772, done.
	remote: Total 772 (delta 0), reused 0 (delta 0), pack-reused 772
	Receiving objects: 100% (772/772), 557.85 KiB | 301.00 KiB/s, done.
	Resolving deltas: 100% (436/436), done.
	Checking connectivity... done.
	
	C:\php-sdk\php70dev\ext>git clone https://github.com/m6w6/ext-propro propro
	Cloning into 'propro'...
	remote: Counting objects: 599, done.
	remote: Total 599 (delta 0), reused 0 (delta 0), pack-reused 599
	Receiving objects: 100% (599/599), 311.29 KiB | 367.00 KiB/s, done.
	Resolving deltas: 100% (354/354), done.
	Checking connectivity... done.
	
	C:\php-sdk\php70dev\ext>cd ..
	
	C:\php-sdk\php70dev>buildconf
	Rebuilding configure.js
	Now run 'configure --help'
	
	C:\php-sdk\php70dev>cscript /nologo configure.js --with-curl --enable-propro --enable-raphf --enable-http
	Saving configure options to config.nice.bat
	Checking for cl.exe ...  <in default path>
	  Detected compiler MSVC14 (Visual C++ 2015)
	  Detected 32-bit compiler
	Checking for link.exe ...  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN
	Checking for nmake.exe ...  <in default path>
	Checking for lib.exe ...  <in default path>
	Checking for bison.exe ...  <in default path>
	Checking for re2c.exe ...  <in default path>
	  Detected re2c version 0.13.5
	Checking for zip.exe ...  <in default path>
	Checking for lemon.exe ...  <not found>
	Checking for mc.exe ...  C:\Program Files (x86)\Windows Kits\8.1\bin\x86
	Checking for mt.exe ...  C:\Program Files (x86)\Windows Kits\8.1\bin\x86
	Enabling multi process build
	
	Build dir: C:\php-sdk\php70dev\Release_TS
	PHP Core:  php7ts.dll and php7ts.lib
	
	Checking for wspiapi.h ...  <in default path>
	Enabling IPv6 support
	Enabling SAPI sapi\cgi
	Enabling SAPI sapi\cli
	Enabling extension ext\bcmath
	Enabling extension ext\calendar
	Checking for library oleaut32.lib ... <in LIB path> OleAut32.Lib
	Enabling extension ext\com_dotnet
	Checking for mscoree.h ...  <in default path>
	Enabling extension ext\ctype
	Checking for library libcurl_a.lib;libcurl.lib ... ..\win32build\lib\libcurl_a.lib
	Checking for curl/easy.h ...  C:\php-sdk\win32build\include
	Checking for library ssleay32.lib ... ..\win32build\lib\ssleay32.lib
	Checking for library libeay32.lib ... ..\win32build\lib\libeay32.lib
	Checking for library winmm.lib ... <in LIB path> WinMM.Lib
	Checking for library wldap32.lib ... <in LIB path> Wldap32.Lib
	Enabling extension ext\curl [shared]
	Enabling extension ext\date
	Enabling extension ext\filter
	Enabling extension ext\ftp [shared]
	Checking for openssl/ssl.h ...  C:\php-sdk\win32build\include
	Checking for library ssleay32.lib ... ..\win32build\lib\ssleay32.lib
	Checking for library libeay32.lib ... ..\win32build\lib\libeay32.lib
	Enabling SSL support for ext\ftp
	Checking for library libjpeg_a.lib;libjpeg.lib ... ..\win32build\lib\libjpeg_a.lib
	Checking for library freetype_a.lib;freetype.lib ... ..\win32build\lib\freetype_a.lib
	Checking for ft2build.h ...  C:\php-sdk\win32build\include
	Checking for library libpng_a.lib;libpng.lib ... ..\win32build\lib\libpng_a.lib
	Checking for gd.h ...  ext\gd\libgd
	Checking for png.h ...  C:\php-sdk\win32build\include
	Checking for library libiconv_a.lib;libiconv.lib ... ..\win32build\lib\libiconv_a.lib
	Checking for iconv.h ...  C:\php-sdk\win32build\include
	Checking for library libXpm_a.lib ... ..\win32build\lib\libxpm_a.lib
	Checking for xpm.h ...  C:\php-sdk\win32build\include\X11
	Checking for library libwebp_a.lib ... <not found>
	Checking for library libwebp.lib ... ..\win32build\lib\libwebp.lib
	Checking for decode.h ...  C:\php-sdk\win32build\include\webp
	Checking for encode.h ...  C:\php-sdk\win32build\include\webp
	Checking for library User32.lib ... <in LIB path> User32.Lib
	Checking for library Gdi32.lib ... <in LIB path> Gdi32.Lib
	Enabling extension ext\gd [shared]
	Enabling extension ext\hash
	Checking for library libiconv_a.lib ... ..\win32build\lib\libiconv_a.lib
	Checking for iconv.h ...  C:\php-sdk\win32build\include
	Enabling extension ext\iconv
	Enabling extension ext\json
	Checking for library ws2_32.lib ... <in LIB path> WS2_32.Lib
	Enabling extension ext\mysqlnd
	Checking for zlib.h ...  ..\zlib
	Enabling extension ext\opcache [shared]
	Enabling extension ext\pcre
	Enabling extension ext\propro
	C:\php-sdk\php70dev\configure.js(1443, 2) Microsoft JScript runtime error: Object doesn't support this property or method

**Comment by m6w6** [comment]
Hm... looks like `AC_DEFINE("PHP_HTTP_HAVE_CLIENT", 1, "Have HTTP client support");` did unexpectedly vanish in config.w32.

Ad missing source file in root: the build system really should not depend on that; I think that's something for the Windows team to fix?

**Comment by Jan-E** [comment]
>Ad missing source file in root: the build system really should not depend on that; I think that's something for the Windows team to fix?

I will create a PR for the Windows build system to fix this
