### ISSUE TITLE
No Content-Length header with empty POST requests

### ISSUE THREAD

**Issue by DicsyDel** [m6w6/ext-http#16]
Hi,

Previously (v 1.7.3) there was always Content-Length header with all POST requests, even with empty post body. What rationale was behind the decision to do not include this header with empty POSTs in 2.X version?

Our issue is that couple API clients stop working after migration, because most of the servers require this header even with empty POSTs (For example most of the Microsoft API endpoints).

According to RFC, nothing bad in including "Content-Length: 0" for empty requests.

Regards,
Igor

**Comment by m6w6** [comment]
I guess we just let curl do it's things in 2.x -- else, I can just remember https://bugs.php.net/68149

Could you please provide a simple repoduce script, so I can double-check?

Thank you!

**Comment by DicsyDel** [comment]
It's simple:

$request = new Request('POST', 'http://example.com');
$this->call($request);

Just POST without any data to any URL. There won't be Content-length header. Right now we've implemented the following workaround:

...
if (in_array($method, ['PUT', 'PATCH', 'POST']) && !isset($headers['Content-Length'])) {
     $request->addHeaders(['Content-Length' => 0]);
}
...

Regards,
Igor

**Comment by m6w6** [comment]
Could you verify that HEAD of R_2_5 works for you? Thanks!

**Comment by DicsyDel** [comment]
Verified. Works perfectly.

Thanks,
Igor

**Comment by m6w6** [comment]
Thank you!
