### ISSUE TITLE
Memory constantly growing

### ISSUE THREAD

**Issue by optyfr** [m6w6/ext-http#23]
I want to send using only 1 client instance lot of requests (100000) using enqueue() + a callback and a send() each 50 requests, but memory keeps constantly growing despite that finished requests are dequeued (count() is never above 50), only a call reset() on client (or destroy then recreate client instance) seems to free memory... it seems to keep references of finished requests is that a normal behaviour? php script is at 128MB around 1500 requests...

Tested on 2.5.5 version with PHP 5.6

**Comment by m6w6** [comment]
Hi! Thanks for the report!

Can you provide a resproduce script?

**Comment by optyfr** [comment]
Hi! here it is
[test.zip](https://github.com/m6w6/ext-http/files/115308/test.zip)

**Comment by optyfr** [comment]
Script output :
 # php test.php

Starting test with 10 send() of 50 POST requests each with 50 random args (500 total requests) limited to 10 total connections...
before pecl_http2:mem used 240 kB
before loop:mem used 242 kB
after send 1:mem used 1943 kB (recvd body subtot: 938 kB)
after send 2:mem used 3642 kB (recvd body subtot: 938 kB)
after send 3:mem used 5343 kB (recvd body subtot: 938 kB)
after send 4:mem used 7039 kB (recvd body subtot: 938 kB)
after send 5:mem used 8800 kB (recvd body subtot: 938 kB)
after send 6:mem used 10505 kB (recvd body subtot: 938 kB)
after send 7:mem used 12202 kB (recvd body subtot: 938 kB)
after send 8:mem used 13898 kB (recvd body subtot: 938 kB)
after send 9:mem used 15723 kB (recvd body subtot: 938 kB)
after send 10:mem used 17420 kB (recvd body subtot: 938 kB)
after loop:mem used 17420 kB (recvd body tot: 9381 kB)
after reset:mem used 455 kB (LEAK is 16964 kB)
after client unset:mem used 454 kB

Starting test with 10 send() of 50 GET requests each with 50 random args (500 total requests) limited to 10 total connections...
before pecl_http2:mem used 449 kB
before loop:mem used 450 kB
after send 1:mem used 2185 kB (recvd body subtot: 938 kB)
after send 2:mem used 3918 kB (recvd body subtot: 938 kB)
after send 3:mem used 5652 kB (recvd body subtot: 938 kB)
after send 4:mem used 7386 kB (recvd body subtot: 938 kB)
after send 5:mem used 9119 kB (recvd body subtot: 938 kB)
after send 6:mem used 10853 kB (recvd body subtot: 938 kB)
after send 7:mem used 12587 kB (recvd body subtot: 938 kB)
after send 8:mem used 14321 kB (recvd body subtot: 938 kB)
after send 9:mem used 16055 kB (recvd body subtot: 938 kB)
after send 10:mem used 17789 kB (recvd body subtot: 938 kB)
after loop:mem used 17789 kB (recvd body tot: 9381 kB)
after reset:mem used 455 kB (LEAK is 17333 kB)
after client unset:mem used 454 kB

Starting test with 10 send() of 50 GET requests each with 0 random args (500 total requests) limited to 10 total connections...
before pecl_http2:mem used 449 kB
before loop:mem used 450 kB
after send 1:mem used 2087 kB (recvd body subtot: 938 kB)
after send 2:mem used 3720 kB (recvd body subtot: 938 kB)
after send 3:mem used 5353 kB (recvd body subtot: 938 kB)
after send 4:mem used 6986 kB (recvd body subtot: 938 kB)
after send 5:mem used 8619 kB (recvd body subtot: 938 kB)
after send 6:mem used 10252 kB (recvd body subtot: 938 kB)
after send 7:mem used 11884 kB (recvd body subtot: 938 kB)
after send 8:mem used 13517 kB (recvd body subtot: 938 kB)
after send 9:mem used 15150 kB (recvd body subtot: 938 kB)
after send 10:mem used 16783 kB (recvd body subtot: 938 kB)
after loop:mem used 16783 kB (recvd body tot: 9381 kB)
after reset:mem used 454 kB (LEAK is 16329 kB)
after client unset:mem used 453 kB

**Comment by optyfr** [comment]
Some other remarks on that test :
the server side script is simply <?=phpinfo(1)?>
modifying phpinfo option to make body size response different will change mem leak size but it is not directly related on the body size since bigger body size may result to less memory leak!

**Comment by m6w6** [comment]
Hey, thanks a lot for your efforts, but this is not a bug.

PHP does not immediately free memory, try the following for clarification:

First, put a gc_collect_cycles() after `$client->send()`, you'll notice that your LEAK output has significantyl decreased.
Second, use `memory_get_usage(TRUE)`, you should see a `0` for your LEAK output.

PS:
> modifying phpinfo option to make body size response different will change mem leak size but it is not directly related on the body size since bigger body size may result to less memory leak!

That's because above a certain threshold, the temporary PHP streams used for response bodies change from being placed in memory to being written to a temporary file.

Cheers!

**Comment by optyfr** [comment]
ok then If i call gc_collect_cycles() after each $client->send() I get :

> Starting test with 10 send() of 50 POST requests each with 50 random args (500 total requests) limited to 10 total connections...
before pecl_http2:mem used 241 kB
before loop:mem used 242 kB
after send 1:mem used 2200 kB (recvd body subtot: 938 kB)
after send 2:mem used 4156 kB (recvd body subtot: 938 kB)
after send 3:mem used 6113 kB (recvd body subtot: 938 kB)
after send 4:mem used 8067 kB (recvd body subtot: 938 kB)
after send 5:mem used 10085 kB (recvd body subtot: 938 kB)
after send 6:mem used 12046 kB (recvd body subtot: 938 kB)
after send 7:mem used 14000 kB (recvd body subtot: 938 kB)
after send 8:mem used 15954 kB (recvd body subtot: 938 kB)
after send 9:mem used 18035 kB (recvd body subtot: 938 kB)
after send 10:mem used 19989 kB (recvd body subtot: 938 kB)
after loop:mem used 19989 kB (recvd body tot: 9381 kB)
after reset:mem used 14537 kB (LEAK is 5451 kB)
after client unset:mem used 14536 kB

So yes the "LEAK" is only 5M but at the same time after calling reset this does not reduce to 424KB anymore even if I put again gc_collect_cycles also after the reset() call, the "LEAK" is a diff between mem before and after reset

Now if I do 100 loops send of 50 requests each, the scripts ends with outofmemory (memory_limit set to 128M) :

> PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 89 bytes) in /root/test.php on line 33

with or without gc_collect_cycles call, the gc should have done its job but that's not the case, and the only reason for gc not doing its job is when references are kept on object so that they can't be freed...

**Comment by m6w6** [comment]
Mhm, okay, thanks for getting back with that note!
I'll have a deeper look.

**Comment by m6w6** [comment]
Okay, it's because the client still holds all the received responses.
To clear them out, either use `$client->reset()` or `while($client->getResponse());`

**Comment by optyfr** [comment]
ultimate results with memory_limit set to 128MB :
200 send() of 50 POST requests with no call to reset() at all : outofmemory after 1950 requests (39 sends)
200 send() of 50 POST requests with call to reset() after each send() : outofmemory after 5000 requests, 100 send()
200 send() of 50 POST requests with unset/new client object after each send : no OOM, mem peak was only 1513KB from the first send and never growed more until the last one

**Comment by optyfr** [comment]
that's better with reset but it seems to keep more than finished responses

**Comment by m6w6** [comment]
Your test script runs fine for me when responses were collected constantly printing `mem used 25x kB`.

**Comment by m6w6** [comment]
Even with a 3M memory limit...

**Comment by optyfr** [comment]
try to feed requests with 50 args, it will eat 128MB for 5000 requests
Seems that references to Request and/or QueryString objects are kept too!

**Comment by m6w6** [comment]
Like that?

```
memory_limit=100M

Starting test with 10 send() of 1000 POST requests each with 50 random args (10000 total requests) limited to 30 total connections...
before pecl_http2:mem used 244 kB
before loop:mem used 244 kB
after send 1:mem used 32191 kB (recvd body subtot: 18763 kB)
after collecting 1000 responses:mem used 729 kB
after send 2:mem used 32184 kB (recvd body subtot: 18763 kB)
after collecting 1000 responses:mem used 729 kB
after send 3:mem used 32173 kB (recvd body subtot: 18763 kB)
after collecting 1000 responses:mem used 729 kB
after send 4:mem used 32178 kB (recvd body subtot: 18763 kB)
after collecting 1000 responses:mem used 729 kB
after send 5:mem used 32181 kB (recvd body subtot: 18763 kB)
after collecting 1000 responses:mem used 729 kB
after send 6:mem used 32189 kB (recvd body subtot: 18763 kB)
after collecting 1000 responses:mem used 729 kB
after send 7:mem used 32180 kB (recvd body subtot: 18763 kB)
after collecting 1000 responses:mem used 729 kB
after send 8:mem used 32181 kB (recvd body subtot: 18763 kB)
after collecting 1000 responses:mem used 729 kB
after send 9:mem used 32185 kB (recvd body subtot: 18763 kB)
after collecting 1000 responses:mem used 729 kB
after send 10:mem used 32189 kB (recvd body subtot: 18763 kB)
after collecting 1000 responses:mem used 729 kB
after loop:mem used 729 kB (recvd body tot: 187636 kB)
```
Okay, let me gather some infos:

Platform?
PHP version?
libcurl version?
`php --ri http`
`php --ri raphf`
`php --ri propro`

Thanks!

**Comment by optyfr** [comment]
With same parameters, I get OOM at send nb4

Here are the infos :
Linux Gentoo AMD64
PHP 5.6.14
Curl 7.45.0


# php --ri http

http

HTTP Support => enabled
Extension Version => 2.5.5

Used Library => Compiled => Linked
libz => 1.2.8 => 1.2.8
libcurl => 7.45.0 => 7.45.0
libevent => 2.0.22-stable => 2.0.22-stable
libidn (IDNA2003) => 0.28 => unknown

Directive => Local Value => Master Value
http.etag.mode => crc32b => crc32b

 # php --ri raphf

raphf

Resource and persistent handle factory support => enabled
Extension version => 1.1.2

                    Persistent handles in this thread
Provider => Ident => Used => Free

Directive => Local Value => Master Value
raphf.persistent_handle.limit => -1 => -1


 # php --ri propro

propro

Property proxy support => enabled
Extension version => 1.0.2

**Comment by optyfr** [comment]
ok, I recopied again the original script on my test server and I can't reproduce it anymore, don't know what was the mistake...
btw is there any reason to keep all the finished responses? I'd like to chain addqueue in callbacks (continuously feed the queue according responses) so that to get only one send for 100000 requests but for the instance, it's not possible to call getResponse in current request callback...

**Comment by m6w6** [comment]
Yes, there is a reason, not everybody uses the queue callback.

> it's not possible to call getResponse in current request callback...

Just tried that, you can call `$client->getResponse();` in the callback, though, to pop the response off the stack. That even keeps the memory footprint low during the loop.

**Comment by optyfr** [comment]
I tried in the callback $client->getResponse($current_cb_request) but it replied that it can't find the response for that request, so I would suppose that calling $client->getResponse() would pop the n-1 request because response is pushed on the stack after callback return, isn't it?

**Comment by optyfr** [comment]
> Yes, there is a reason, not everybody uses the queue callback.

ok, so would it be possible then to not keep response when a callback use is detected and returning true?

**Comment by m6w6** [comment]
> I tried in the callback $client->getResponse($current_cb_request) but it replied that it can't find the response for that request

That's strange, I'll check that.

> so I suppose that calling $client->getResponse() would pop the n-1 request because response is pushed on the stack after callback return, isn't it?

No, it's pushed right before invoking the callback: https://github.com/m6w6/ext-http/blob/v2.5.x/src/php_http_client.c#L423 -- but, right, how should you know that? :)

There wouldn't be any `n-1`, though, if every response is popped.

**Comment by m6w6** [comment]
> ok, so would it be possible then to not keep response when a callback use is detected and returning true?

Possible? Sure, but BC breaks, you know... :-/

**Comment by optyfr** [comment]
ok, so let's go for popping in callback... anyway it would be good to mention in the documentation that responses are always pushed/kept in the "internal storage" even if callback is used and returning true and hence the need to be popped with getResponse() if not needed anymore

**Comment by m6w6** [comment]
Yes, thanks for going through this! Many others would have left in despair.
If you want to improve on the docs in the meantime, you can easily send PRs by clicking on the red "Edit" link in the top right corner of the docs: https://mdref.m6w6.name/http/Client

Thanks a lot!

**Comment by optyfr** [comment]
Thanks, didn't know I could do that by myself! I've just made the edit and a pull request, hope my sentence is ok for you

**Comment by m6w6** [comment]
Thank you very much! I hope, you don't mind the slight re-wording :-)
