### ISSUE TITLE
Call to undefined function http_build_url()

### ISSUE THREAD

**Issue by dyeshurun** [m6w6/ext-http#27]
Were procedural functions removed from the new version? (3.0)

**Comment by remicollet** [comment]
They where removed in httpd v2

**Comment by dyeshurun** [comment]
I see, we are still in 1.7.6...Upgrading to php7

**Comment by m6w6** [comment]
Version Matrix:

pecl_http/PHP | 4.3 | 4.4 | 5.0 | 5.1 | 5.2 | 5.3 | 5.4 | 5.5 | 5.6 | 7.0
---|---|---|---|---|---|---|---|---|---|---
1.x | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :o2: | :o2: | :o2: | :o2:
2.x |  :o2: | :o2: | :o2: | :o2: | :o2: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :o2:
3.x |  :o2: |  :o2: |  :o2: |  :o2: |  :o2: |  :o2: |  :o2: |  :o2: |  :o2: | :white_check_mark:
