### ISSUE TITLE
http\Message::getInfo() is misleading

### ISSUE THREAD

**Issue by dgwynne** [m6w6/ext-http#29]
The documentation states that this will "Retrieve the first line of a request", but it is inconsistent with what actually ends up on the wire.

For example, the following:

``` .php
$req = new http\Client\Request('GET', 'http://www.php.net/');
printf("%s\n", $req->getInfo());
```

outputs:

```
$ php getInfo.php
GET http://www.php.net/ HTTP/1.1
```

However, when running tcpdump -A, i see:

```
GET / HTTP/1.1
```

I'm arguing that getInfo() should represent what goes on the wire. It would also be nice if a new `http\Client\Request` object would have its `$headers` initialised with what will go on the wire too, specifically the Host header.

Cheers,
dlg

**Comment by m6w6** [comment]
Yeah, uhm... well, no? ;) Sorry, let me explain.

We (or rather http\Message) actually do(es) not know what's going over the wire. http\Message is actually pretty dumb, and http\Client\Request is not much cleverer :) http\Message::getInfo() is barely more than `return sprintf("%s %s HTTP/%s", $method, $url, version);`

**Comment by dgwynne** [comment]
i understand, and my guess is that is because you offload the wire handling to curl.

the reason i asked is cos i was trying to get the request line and host header to feed into a signature to authenticate a request. it seems awkward having to write code around http\Client\Request (like parse_url to get the host and path+query, and my own sprintf for the request line) to figure these things out. the Request ends up figuring it out in the end, i just want to get access to that processing a bit earlier rather than doing it again myself.

**Comment by rcanavan** [comment]
Since 1ac722a, the "real" request line can be retrieved via http\Client::setDebug()

@m6w6: could you please fix the documentation or $req->getInfo()?

**Comment by m6w6** [comment]
> @m6w6: could you please fix the documentation or $req->getInfo()?

Not sure what exactly to fix, but I'd be more than happy to accept a PR; just click on the red "Edit" link at the top right of any mdref page: https://github.com/m6w6/mdref-http/edit/master/http/Message/getInfo.md
