### ISSUE TITLE
http\Server

### ISSUE THREAD

**Issue by ParkFramework** [m6w6/ext-http#30]
Hi.

You want to do, the server `http\Server`?
Use `libevent`, but better `libuv`
https://github.com/bwoebi/php-uv

In PHP this is not enough.
Thank.

**Comment by m6w6** [comment]
There already is pecl/swoole. Did you try that?

http://pecl.php.net/package/swoole
Am 18.03.2016 16:36 schrieb "S.A.N" <notifications@github.com>:

**Comment by ParkFramework** [comment]
Yes, already
I it working to improve
https://github.com/swoole/swoole-src/issues/568

But he develops in his direction and poor knowledge of the english language, worse than me :)
