### ISSUE TITLE
Not possible to unset the User-Agent

### ISSUE THREAD

**Issue by yunosh** [m6w6/ext-http#32]
Contrary to CURL, it's not possible to unset the User-Agent request header by setting the 'useragent' configuration option to NULL.

**Comment by m6w6** [comment]
Hi! Thanks for your report.

Looks like that's undocumented, but you can suppress the User-Agent header by setting the `useragent` request option to the empty string. Setting it to `NULL` will cause the library to use its default.

**Comment by yunosh** [comment]
Yes, this seems to work, thanks!
