### ISSUE TITLE
Sending multiple header fields with identical names

### ISSUE THREAD

**Issue by rcanavan** [m6w6/ext-http#34]
As of 3.0.1, ext-http cannot send multiple header fields with identical names, e.g.

`$request->setHeaders('Foo' => Array(0 => 'aaa', 1 => 'bbb')));`

results in a log message  ("PHP Notice:  Array to string conversion in ..../pecl_http.php on line 27") and a request that sends a header:

`Foo: Array`

While headers (excluding a few documented exceptions) can be combined into comma separated lists, not all servers / web applications handle this properly, therefore it is desirable to be able to actually send multiple header fields instead of combining them.

[ext-http-multi-header.patch.txt](https://github.com/m6w6/ext-http/files/195389/ext-http-multi-header.patch.txt)

**Comment by m6w6** [comment]
Thanks for the report!

There's actually some header handling code in the library which does the former (combining the values by comma), but after reconsideration, I think it's best to leave that to the implementer, and not let the library smart-assingly do something the user cannot control.

Thanks.
