### ISSUE TITLE
Persistent curl handles: error code not properly reset

### ISSUE THREAD

**Issue by afflerbach** [m6w6/ext-http#38]
After a curl error (e.g. timeout, failed SSL handshake), the `errorcode` is not properly reset. I'm using  persistent handles. Resetting the `errorcode` in `php_http_curlm_responsehandler` seems to help:

```c
    if (CURLE_OK != msg->data.result) {
        …
    } else {
        st = php_http_curle_get_storage(msg->easy_handle);
        st->errorcode = 0;
        …
    }
```

**Comment by m6w6** [comment]
Thank you for the report!

**Comment by afflerbach** [comment]
Thank you, works as expected!
