### ISSUE TITLE
[phpng] Runtime dependency on raphf isn't resolved by php

### ISSUE THREAD

**Issue by J5lx** [m6w6/ext-http#4]
In /etc/php/conf.d I have these configuration files:
- http.ini:

  ```
  extension=http.so
  ```
- propro.ini:

  ```
  extension=propro.so
  ```
- raphf.ini:

  ```
  extension=raphf.so
  ```

When I execute `php -m` with PHP 7.0.0 Beta 1 [from the AUR](https://aur4.archlinux.org/pkgbase/php7/) and the phpng branches of raphf, propro, and this extension, I get:
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/http.so' - /usr/lib/php/modules/http.so: undefined symbol: php_persistent_handle_abandon in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/http.so' - /usr/lib/php/modules/http.so: undefined symbol: php_persistent_handle_abandon in Unknown on line 0
[PHP Modules]
...
raphf
...
```
which clearly indicates that raphf has for some reason been loaded after http, while http depends on it. Accordingly, http is loaded just fine when I move `extension=raphf.so` from raphf.ini right before `extension=http.so` in http.ini
However, when I disable propro, I get:
```
PHP Warning:  Cannot load module 'http' because required module 'propro' is not loaded in Unknown on line 0

Warning: Cannot load module 'http' because required module 'propro' is not loaded in Unknown on line 0
[PHP Modules]
...
```
Since this time PHP complains about missing modules instead of missing symbols, I'm pretty sure that the raphf error originates from a bug regarding dependency resolution in http. Any thoughts?

**Comment by remicollet** [comment]
load order issue ?
try to rename http.ini to z-http.ini

Notice: some distro have switch to a numerical prefix for all .ini to ensure correct load order

Ex:
    $ ls /etc/php.d
    ...
    20-iconv.ini
    ...
    40-propro.ini
    40-raphf.ini
    ...
    50-http.ini
    ...

**Comment by m6w6** [comment]
Finally figured out why module deps didn't work out as they should with raphf.

**Comment by J5lx** [comment]
Confirmed working, thanks!

**Comment by gustawdaniel** [comment]
In my case fixed by

```
sudo apt install php-raphf
```

**Comment by katoba86** [comment]
sudo apt install php-raphf php-propro fixed myy problem
