### ISSUE TITLE
determine the SSL backend used by curl at runtime

### ISSUE THREAD

**Issue by rcanavan** [m6w6/ext-http#40]
Since the behaviour of ssl/cainfo and ssl/capath depends on the SSL backend used by curl, it would be useful to be able to retrieve this information at runtime. With ext/curl, curl_version() could be used, I'm not aware of any equivalent function in pecl_http.

**Comment by m6w6** [comment]
Fixed in 13b8cf3a7dfb62a33876547d6026effe8156af41
