### ISSUE TITLE
Joining query with empty original variable in query

### ISSUE THREAD

**Issue by blaaat** [m6w6/ext-http#43]
First of all, i'm not sure i'm running the latest version, but couldn't find anything about this in the changelogs.

When you join query and the original parameter value is empty, it's removed from the modifies query string.

Example: 

> $hurl = new http\url("http://www.google.com/?a"); 
> 
> $hurl = $hurl->mod(array(
> 										'query' => 'b=3'),
> 									http\url::JOIN_QUERY
> 										);
> $url = $hurl->toString();	
> 

Output: http://www.google.com/?b=3
Expected output: http://www.google.com/?a&b=3

**Comment by blaaat** [comment]
This isn't working the other way around either (by adding 'b=') without value.

**Comment by m6w6** [comment]
If you're running on PHP5, you can try the tip of https://github.com/m6w6/ext-http/tree/v2.6.x to verify a possible fix.
