### ISSUE TITLE
Parsing of improperly %-encoded URLs fails

### ISSUE THREAD

**Issue by afflerbach** [m6w6/ext-http#48]
```php
<?php

$url = 'https://de.wikipedia.org/w/index.php?title=%';

$client = new http\Client();
$request = new http\Client\Request('GET', $url);
$client->enqueue($request);
```

throws an exception
 
```sh
$ php -ddisplay_errors=1 /tmp/test.php

Warning: http\Client\Request::__construct(): Failed to parse query; invalid percent encoding at pos 6 in 'title=%' in /tmp/test.php on line 6

Warning: http\Client\Request::__construct(): Failed to parse URL query: '%' in /tmp/test.php on line 6

Fatal error: Uncaught http\Exception\RuntimeException: http\Client::enqueue(): Cannot request empty URL in /tmp/test.php:7
Stack trace:
#0 /tmp/test.php(7): http\Client->enqueue(Object(http\Client\Request))
#1 {main}
  thrown in /tmp/test.php on line 7
```

Compared to the behavior of other clients (Firefox, Chrome, curl, wget) the URL parsing appears to be too strict here. So for consistency with other clients, `%` characters *not* followed by two hex digits should be silently treated as `%25`.

**Comment by m6w6** [comment]
Let me think about that. Maybe we'd need to introduce another http\Url flag.

**Comment by m6w6** [comment]
Sort of implemented in https://github.com/m6w6/ext-http/commit/4c7a60297b3aaae7edd8337144a83039c9633d71

See https://mdref.m6w6.name/http/Url#IGNORE_ERRORS and https://mdref.m6w6.name/http/Url#SILENT_ERRORS
