### ISSUE TITLE
http\Url uses http request path by default

### ISSUE THREAD

**Issue by recipe** [m6w6/ext-http#51]
### We have found an issue with `http\Url` class. 
Steps to reproduce: If you create apache site with document root pointed to the directory with this file `test.php` and open an url `http://localhost/test.php` it behaves incorrectly. 

```php
//test.php
use http\Url;

$url2 = new Url('http://foo.bar');
$url2->port = '123';

var_dump("$url2");
string 'http://foo.bar:123/test.php' (length=27)
```

If you use cli to run php ./test.php it works well returning `string(19) "http://foo.bar:123/"`

**Comment by m6w6** [comment]
Unfortunately, this is not a bug. but a feature, unless you're on v3/PHP7.

In v2, http\Url's [constructor](https://mdref.m6w6.name/http/Url/__construct) has [http\Url::FROM_ENV](https://mdref.m6w6.name/http/Url#FROM_ENV) as default flags...
