### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by surjit** [m6w6/ext-http#59]
I have installed http and required extension on ubuntu 16.04 
PHP Version 7.0

getting this error
/usr/sbin/apache2: symbol lookup error: /usr/lib/php/20151012/http.so: undefined symbol: uidna_IDNToASCII

thanks

**Comment by surjit** [comment]
it seems, I'm missing some other extension or linux package, please advise

**Comment by afflerbach** [comment]
Sounds pretty much like [this](/m6w6/ext-http/commit/2e92ec7#commitcomment-19517000).

So you could either build `--without-http-libicu-dir` or install the [`libicu-dev`](http://packages.ubuntu.com/xenial/libicu-dev) package.

**Comment by afflerbach** [comment]
I don't think I would consider this issue resolved. Mike?

**Comment by m6w6** [comment]
Yes, seems like something to look into, thanks!

**Comment by surjit** [comment]
I think compilation should not move forward until dependencies installed

**Comment by m6w6** [comment]
@surjit Any chance you've got the old `config.log` around, so I start with the right track?

**Comment by surjit** [comment]
I have to reinstalled it, actually i tried it on vmware

**Comment by alsultanca** [comment]
I have the same issue on CentOS 6.8

error: /opt/cpanel/ea-php71/root/usr/lib64/php/modules/http.so: undefined symbol: uidna_IDNToASCII

**Comment by khavishbhundoo** [comment]
Just a heads up getting the same issue on centos 7 running php 7.1.2

**Comment by remicollet** [comment]
@khavishbhundoo use my [repo](https://rpms.remirepo.net/wizard/), you will have latest PHP and most of extensions ;)

**Comment by khavishbhundoo** [comment]
@remicollet I already use your remi...i just forgot to install http using your repo
For anyone else reading this you can try the following command to install this extension.
`yum --enablerepo=remi,remi-php71 install php-pecl-http`

**Comment by MatthewBooth** [comment]
> Sounds pretty much like [this](/m6w6/ext-http/commit/2e92ec7#commitcomment-19517000).
> 
> So you could either build `--without-http-libicu-dir` or install the [`libicu-dev`](http://packages.ubuntu.com/xenial/libicu-dev) package.

This worked for me in 2020.

**Comment by afflerbach** [comment]
[GitHub 2020 compatible link to the issue](/m6w6/ext-http/commit/2e92ec7#r19514912).
