### ISSUE TITLE
Fails to build when curl has been compiled against gnutls

### ISSUE THREAD

**Issue by fpoirotte** [m6w6/ext-http#62]
Hi,

While trying to install the latest release of the extension on my system (Debian Stretch with curl compiled against GnuTLS & PHP 7.1.2), I got the following error:
```
...
 cc -I. -I/home/me/php-7.1.2/pear/temp/pecl_http -DPHP_ATOM_INC -I/home/me/php-7.1.2/pear/temp/pear-build-merpMd3I/pecl_http-3.1.0/include -I/home/me/php-7.1.2/pear/temp/pear-build-merpMd3I/pecl_http-3.1.0/main -I/home/me/php-7.1.2/pear/temp/pecl_http -I/home/me/php-7.1.2/include/php -I/home/me/php-7.1.2/include/php/main -I/home/me/php-7.1.2/include/php/TSRM -I/home/me/php-7.1.2/include/php/Zend -I/home/me/php-7.1.2/include/php/ext -I/home/me/php-7.1.2/include/php/ext/date/lib -I/home/me/php-7.1.2/include/php/ext/raphf -I/home/me/php-7.1.2/include/php/ext/propro -I/home/me/php-7.1.2/pear/temp/pecl_http/sr
c -DHAVE_CONFIG_H -g -O2 -c /home/me/php-7.1.2/pear/temp/pecl_http/src/php_http_client_curl.c  -fPIC -DPIC -o src/.libs/php_http_client_curl.o
/home/me/php-7.1.2/pear/temp/pecl_http/src/php_http_client_curl.c:24:21: fatal error: gnutls.h: No such file or directory
 # include <gnutls.h>
                     ^
compilation terminated.
Makefile:220: recipe for target 'src/php_http_client_curl.lo' failed
make: *** [src/php_http_client_curl.lo] Error 1
ERROR: `make' failed
```

On Debian, the header is located in gnutls/gnutls.h and not gnutls.h. Also, every example I could find on GnuTLS' website (eg. https://www.gnutls.org/manual/html_node/Echo-server-with-X_002e509-authentication.html) use the former location.
My guess is that this is just a typo, but I don't know much about GnuTLS.

Also, I can confirm that changing the path results in the http.so file being built correctly (I haven't tested it against any SSL/TLS-protected site though)

Best regards,
François

**Comment by m6w6** [comment]
Uhm, that should already be caught at configure time...

**Comment by m6w6** [comment]
Hi, can you share your `config.log`? Thank you.

**Comment by m6w6** [comment]
Should be fixed in https://github.com/m6w6/ext-http/commit/ba994a971deb5cd596f2348e865117bd4208a093
