### ISSUE TITLE
Url::mod() breaks query strings containing plus-notation spaces in the input URL

### ISSUE THREAD

**Issue by signe** [m6w6/ext-http#63]
When the URL being modified contains parameters that utilize the plus-notation for spaces, mod() re-encodes these values as %2B (encoded plus-sign) instead of as either + or %20 (space).

```
$url = 'http://example.com/?param=has+spaces';
$query = ['foo' => 'bar'];
$parts['query'] = new QueryString($query);
echo (new Url($url, null, Url::STDFLAGS))->mod($parts)->toString();
```
prints `"http://example.com/?param=has%2Bspaces&foo=bar"`

Using %20 or ' ' in the source URL properly returns `"http://example.com/?param=has%20spaces&foo=bar"`

At first I thought this was a side-effect of STDFLAGS including PARSE_TOPCT, but disabling that has no effect.

**Comment by m6w6** [comment]
Ugh, we use rawurl{en,de}code internally.

Not sure how to fix this.

**Comment by recipe** [comment]
All parameters that come with `$url` variable should be parsed and decoded internally before being composed with additional parameters that come with `mod`. The all should be encoded again to string.

**Comment by m6w6** [comment]
Yeah, we do. But rawurldecode()/rawurlencode().

**Comment by recipe** [comment]
We can do `urldecode` instead to encode `url` parameters. Then we can use `rawurlencode` everywhere. First method should successfully decode all strings that were encoded by the second.  
```var_dump(rawurlencode(urldecode('has+spaces')));```

**Comment by m6w6** [comment]
So, who's "we" in that case?

**Comment by recipe** [comment]
@m6w6 :) sorry I'am not an C programmer and can not create PR for this issue.

**Comment by m6w6** [comment]
Oh, I was under the wrong impression, that `urldecode` wouldn't decode `%20` additionally to `+`.
