### ISSUE TITLE
 php-fpm[25241]: segfault at 80 ip 00007f84ac90e471 sp 00007ffc538f1450 error 4 in http.so[7f84ac8f6000+70000]

### ISSUE THREAD

**Issue by jos666** [m6w6/ext-http#71]
php-fpm[25241]: segfault at 80 ip 00007f84ac90e471 sp 00007ffc538f1450 error 4 in http.so[7f84ac8f6000+70000]
PHP 5.4.45  http 2.6.0

**Comment by m6w6** [comment]
I'd definitely need more info on that.
