### ISSUE TITLE
unexpected high Memory use when POSTing huge files

### ISSUE THREAD

**Issue by rcanavan** [m6w6/ext-http#75]
The test script below, when fed with a large_file with 100s of Megabytes consumes large amounts of memory (not just virtual, but actual RSS), approximately equal to the size of the file, apparently after the request has been sent.

```<?php
echo "Test\n";

$request = new http\Client\Request;
$file=fopen("/tmp/large_file", "r");
$fbody= new http\Message\Body($file);
$request->setBody($fbody);
$request->setRequestMethod("POST");
$request->setRequestUrl("http://localhost:14080/x.php");
$client = new http\Client;
//$client->recordHistory = true;
$client->enqueue($request)->send();
echo "done\n\n";
```
No such excessive memory use is observed with a simple libcurl test program such as https://curl.haxx.se/libcurl/c/fileupload.html

**Comment by m6w6** [comment]
Hmm, I cannot reproduce. Maximum (`valgrind --tool=massif`) for a 300M upload showed 3.1M memory usage.

**Comment by rcanavan** [comment]
OK, I can't currently reproduce this either, so I suppose I've messed up something while testing.
