### ISSUE TITLE
Error loading http.so

### ISSUE THREAD

**Issue by Dundee** [m6w6/ext-http#76]
I get error `undefined symbol: php_property_proxy_object_new_ex` when trying to load the extension.

Any ideas how to solve this?

PHP: 7.2.1 (cli) (built: Jan  3 2018 06:02:01) ( NTS )
OS: Archlinux
Kernel: 4.14.13-1-ARC

**Comment by m6w6** [comment]
Do you have current versions of its dependencies (pecl/propro in this case) installed and loaded?

**Comment by Dundee** [comment]
Ah, thanks for the clue. The problem was in the naming of /etc/php/conf.d files which loaded http.ini before propro.ini.
