### ISSUE TITLE
How can i stop redirects using pecl_http ? 

### ISSUE THREAD

**Issue by sujayvenaik** [m6w6/ext-http#77]
How can i stop redirects using pecl_http ?

**Comment by m6w6** [comment]
Could you elabroate? When issuing a request or response?

**Comment by sujayvenaik** [comment]
Request.
Say i enter request for http://www.google.com.
I dont want it to redirect to htp://www.google.co.in or some other county domain.
@m6w6

**Comment by sujayvenaik** [comment]
i think i got the solution
`$request->setOptions(array('redirect' => true));`

Correct me if i am wrong.

**Comment by m6w6** [comment]
Set it to zero or false: https://mdref.m6w6.name/http/Client/Curl#$redirect

**Comment by m6w6** [comment]
Alright, closing then.
