### ISSUE TITLE
PHP 7.3

### ISSUE THREAD

**Issue by Jan-E** [m6w6/ext-http#78]
@m6w6 Now that you are awake and working on the extensions: could you try to fix the PHP 7.3 compatibility? See https://externals.io/message/102338#102448

**Comment by Jan-E** [comment]
Bummer. If I load php 7.3.0 alpha2 (x64, nts) with all the extensions that compile at the moment, it crashes on a script with phpinfo();
![pecl_http](https://user-images.githubusercontent.com/1757825/41919120-0939568c-795e-11e8-8206-2c96d7850487.png)

**Comment by m6w6** [comment]
Yeah, there seems to be another issue with 7.3/master, too.

**Comment by m6w6** [comment]
https://travis-ci.org/m6w6/ext-http/jobs/396893858

**Comment by Jan-E** [comment]
It does not crash with only curl, propro, raphf and http loaded, so there must be something more to it. The debugger points to php_http_optons.c so maybe you've got a clue. I will try to gradually unload all other extensions to see if I can pinpoint something. That is, when I can find the time.

**Comment by Jan-E** [comment]
With this php.ini:
```
[PHP]
extension_dir = "ext"
extension=propro
extension=raphf
extension=http      ; Must be after propro and raphf as it depends on it
```
`php -m` leads to a `zend_mm_heap corrupted` or to an unhandled exception, at random one of the two. Dist here:
https://phpdev.toolsforresearch.com/php-7.3.0alpha2-nts-Win32-VC15-x64.htm
https://phpdev.toolsforresearch.com/php-7.3.0alpha2-nts-Win32-VC15-x64.zip (in about 15 minutes)

**Comment by m6w6** [comment]
Found the issue: 377d576a
https://travis-ci.org/m6w6/ext-http/builds/396940302

**Comment by remicollet** [comment]
I confirm, build + test suite OK with 7.3.0alpha2

Thanks

**Comment by Jan-E** [comment]
Yes, seems OK. Side effect of https://externals.io/message/102338#102451 ??

**Comment by Jan-E** [comment]
OK. Yet another thing that has to be added to UPGRADING.INTERNALS
