### ISSUE TITLE
Where to find a valid PHP stub file?

### ISSUE THREAD

**Issue by Leeo97one** [m6w6/ext-http#83]
I'm currently using [the one provided by JetBrains](https://github.com/JetBrains/phpstorm-stubs/blob/master/http/http3.php) but it lacks PHPDoc.

Where can I find a complete stub?

**Comment by m6w6** [comment]
I'm experimenting with generating one out of  https://mdref.m6w6.name/http i.e. https://github.com/mdref/mdref-http.git

Here's a first result: https://gist.github.com/m6w6/49b10cf182d563b47dc1b28c7c1a2644

**Comment by Leeo97one** [comment]
Thanks! I'll try it ASAP and make a pull request on the JetBrains repo if it's OK.

**Comment by Leeo97one** [comment]
Overall it looks good but the default value of optional parameter is missing from some functions.
For exemple: the `$cb` parameter from the `Client::enqueue` function or `$request` from `Client::getResponse`.

**Comment by m6w6** [comment]
Thank you for the feedback, I'll look into that

**Comment by m6w6** [comment]
Stub files are now available in the docs repo: https://github.com/mdref/
And can be downloaded from the docs website: http://mdref.m6w6.name/

**Comment by Leeo97one** [comment]
Excellent, thanks!
