### ISSUE TITLE
[Question] Migration from php curl to pecl http: five fold increase in processes

### ISSUE THREAD

**Issue by Slind14** [m6w6/ext-http#87]
Hi,
we migrated from php's curl implementation to pecl-http in order to be able to reuse existing connections and avoid hitting limitations there.

With the migration we experienced a five fold increase of current processes. Are we missing something?

```php
        $client = new http\Client('curl', 'globalHandle');
        $request = new http\Client\Request;
        $reqQuery = new http\QueryString("user=" . $config['username'] . "&password=" . $config['password'] . "&max_execution_time=3&enable_http_compression=1&query=".urlencode($queryParts[0] . 'VALUES'));
        $body = new http\Message\Body;
        $body->append($queryParts[1]);
        $request->setOptions([ 'timeout' => 1, 'connecttimeout' => 1 ]);
        $request->setRequestUrl($url);
        $request->setQuery($reqQuery);
        $request->setRequestMethod('POST');
        $request->setBody($body);
        $client->enqueue($request);
        $client->send();
```

(Migration happened on the 11th)
![image](https://user-images.githubusercontent.com/3914677/52889085-bb541180-317e-11e9-8bfa-2567e4ac517a.png)
![image](https://user-images.githubusercontent.com/3914677/52889094-c149f280-317e-11e9-9928-89177f28683d.png)
Requests stayed (more or less) the same:
![image](https://user-images.githubusercontent.com/3914677/52889101-c6a73d00-317e-11e9-89d0-31cb01e7f47f.png)

**Comment by m6w6** [comment]
Hi, this is probably due to the type of resolver libcurl was built with, i.e. threaded resolver.

**Comment by Slind14** [comment]
Is there anything I could do to reduce this? I had to dump open files immensely.

**Comment by m6w6** [comment]
I guess you could build libcurl with the threaded resolver disabled, or presumably better, with the async resolver (c-ares) instead.

**Comment by Slind14** [comment]
So kinda like this? https://stackoverflow.com/a/41986646/2693017
I have never done anything like it yet.

**Comment by m6w6** [comment]
How did it go?

**Comment by Slind14** [comment]
I haven't found the time to do it yet.

**Comment by m6w6** [comment]
Thinking again about it, the threaded resolver should have been already in use with ext/curl, so it seems unlikely the threaded resolver is the /actual/ problem.

Where's the data from the graphs coming from? What's the big drop in the second one?

**Comment by Slind14** [comment]
The data is from https://amplify.nginx.com/
The drop in the second one is from switching from php curl to pecl. (the php curl one doesn't reuse connections)

**Comment by m6w6** [comment]
Hm, sorry, still doesn't make a lot of sense to me...

**Comment by m6w6** [comment]
Checking their [docs](https://amplify.nginx.com/docs/guide-metrics-and-metadata.html#php-fpm-metrics) and see if they help me understand...

**Comment by m6w6** [comment]
max_child: The number of times, the process limit has been reached.

Okay, so the drop was just due to restart.

**Comment by m6w6** [comment]
Don't hesitate to reopen when there are new insights.
