### ISSUE TITLE
Call to undefined function http_build_url() in /var/www/html/newsFeed.php on line 

### ISSUE THREAD

**Issue by akash3456** [m6w6/ext-http#9]
I seem to be getting this error even though all dependencies have been installed?

**Comment by remicollet** [comment]
It seems your code requires old pecl_http v1 (which is not compatible with v2)

**Comment by akash3456** [comment]
I have php 5.6.4 on Ubuntu 15.04.

**Comment by m6w6** [comment]
You either have to install pecl_http-1.7.6 or upgrade your userland code to the v2 API https://mdref.m6w6.name/http
