### ISSUE TITLE
Implement PSR-18

### ISSUE THREAD

**Issue by garak** [m6w6/ext-http#93]
It would be nice it this extension implemented [PSR-18](https://www.php-fig.org/psr/psr-18/)

**Comment by m6w6** [comment]
If it did, it would have to implement PSR-7 as well, and etc, etcpp. The current API of this extension was first released 8 years ago, sorry.

**Comment by garak** [comment]
You can release a major version (so you can break the API)

**Comment by m6w6** [comment]
Sure, right! PRs welcome :wink:
