### ISSUE TITLE
Failed test on bigendian

### ISSUE THREAD

**Issue by remicollet** [m6w6/ext-http#94]
on s390x
```
PASS ranges [tests/envresponseranges001.phpt] 
TEST 100/196 [tests/etag001.phpt]
========DIFF========
022+       gost: ebf286e3239dca92fa5b8f3dd76977918110c2136d3ef6dcb8fe7f54677b030e
023+ gost-crypto: 78ceea6146d8d15baa0f996038981e29ac240e2d107e85acb85a40e492edcea2
022-       gost: efc79cdd01331adf80b30af816ff7a934f3f3df3085294a310918cacff3500f0
023- gost-crypto: 2e6bd37841520cc9ccb8c7abd68bd3ec9ce601651b995f3639090f585cc23684
========DONE========
FAIL etags with hash [tests/etag001.phpt] 

```

**Comment by m6w6** [comment]
I fixed that yearly failing test for ext-http, thanks!

I doubt GOST is supposed to give different hashes on BIG/little endian, feels like a deja vu on the tiger hash fiasco; see php/php-src@4b23428d9d615d7ff26c7410bd1d65d1ec773111

Does the ext/hash/tests/gost.phpt *NOT* fail on BIGendian?

**Comment by remicollet** [comment]
> Does the ext/hash/tests/gost.phpt NOT fail on BIGendian?

See https://kojipkgs.fedoraproject.org//packages/php/7.3.11/1.fc31/data/logs/s390x/build.log

```
TEST 4133/10270 [ext/hash/tests/gost.phpt]
PASS gost [ext/hash/tests/gost.phpt] 
```
