### ISSUE TITLE
Windows PECL DLL builds are failing

### ISSUE THREAD

**Issue by cmb69** [m6w6/ext-http#97]
This is a follow up to m6w6/ext-raphf#7.

`nmake` fails to build pecl_http 3.2.3 with the following error:
````
ext\http\src\php_http_client_curl_event.c(18): fatal error C1083: Cannot open include file: 'event.h': No such file or directory
````
I think [this line](https://github.com/m6w6/ext-http/blob/RELEASE_3_2_3/src/php_http_client_curl_event.c#L18) should be:
````
#include <event2/event.h>
````
or [config.w32](https://github.com/m6w6/ext-http/blob/RELEASE_3_2_3/config.w32#L147) would have to be adjusted:
````
		if (CHECK_HEADER_ADD_INCLUDE("event2/event.h", "CFLAGS_HTTP", null, null, true) &&
````

**Comment by Jan-E** [comment]
Libevent comes with 2 times 'event.h:
https://github.com/libevent/libevent/tree/master/include
https://github.com/libevent/libevent/tree/master/include/event2

I tried to include only the second one by removing the one in my main include dir and checking on 
```
CHECK_HEADER_ADD_INCLUDE("event.h", "CFLAGS_HTTP", PHP_PHP_BUILD + "\\include\\event2;" + PHP_HTTP
```
but this failed:
```
ext\http\src\php_http_client_curl_event.c(30): error C2079: 'evnt' uses undefined struct 'event'
ext\http\src\php_http_client_curl_event.c(264): error C2027: use of undefined type 'event'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe"' : return code '0x2'
```
Both headers have to be there. At configure time it checks if libevent2 is installed and at compile time it includes the event.h in the main include directory.

**Comment by Jan-E** [comment]
@cmb69 Can you check if the latest commit fixes this issue?

**Comment by Jan-E** [comment]
Ugly typo in the commit description:
https://github.com/m6w6/ext-http/commit/85cce2121de3ab8993ee35c1f8d8b8f7c696fd3d

**Comment by cmb69** [comment]
Ah, we're coming closer, thanks! The problem is that our [libevent packages](https://windows.php.net/downloads/pecl/deps/) don't include this header, probably because this header is [deprecated as of libevent 2](https://github.com/libevent/libevent/blob/4436287d1247fb2e9c80560debf852a94657e485/include/event.h#L34-L37). I'll add the missing headers and give it try, but probably this should be resolved in ext-http (I wonder if the include/event.h is used by the Linux builds).

**Comment by cmb69** [comment]
Little by little, the bird builds its nest…

The [builds are ready now](https://windows.php.net/downloads/pecl/releases/http/3.2.3/), but they're not linked on the PECL package page, possibly due to the package name (pecl_http vs. http). I'll have a look at this issue when I'm back on the keyboard.

**Comment by cmb69** [comment]
Indeed, just an issue with rmtools. After manual renaming, the binary builds are available at https://pecl.php.net/package/pecl_http/3.2.3/windows.

**Comment by Jan-E** [comment]
Did you build it with ot without https://github.com/m6w6/ext-http/commit/85cce2121de3ab8993ee35c1f8d8b8f7c696fd3d ?

**Comment by cmb69** [comment]
I built an *unmodified* [3.2.3](https://pecl.php.net/get/pecl_http-3.2.3.tgz) (otherwise I would not have published this as release).

To summarize, there have been two issues:
* the deprecated headers are missing in the libevent dependency package
* the rmtools PECL real_name setting does not produce proper file/foldernames

So everything is fine from your side; of course, 85cce21 makes sense, though.

Sorry for the inconvenience; I'll try to fix the outstanding issues soon.

**Comment by m6w6** [comment]
I was about to release 4.0 stable, but noticed there's no 4.0b1 windows release on pecl, so I guess this is still a problem?

**Comment by cmb69** [comment]
It seems that build never had been attempted. I'm having a look.

**Comment by cmb69** [comment]
Apparently 4.0b1 requires PHP 8.0.0, but we do not do these builds yet; mass rebuilds will be done in a few weeks. I'll trigger a snapshot of 4.0b1, to see whether there are any issues.

**Comment by m6w6** [comment]
NP, thanks a lot Christoph!

**Comment by Jan-E** [comment]
@m6w6 Both the dependent ext-propro as ext-http build without modifications on Windows, so that should not be a reason to delay a 4.0 stable release. It looks ext-propro did not have any essential changes since the last release, but maybe en extra release to indicate that it is PHP 8-ready might be useful.

**Comment by m6w6** [comment]
propro is dead, though, for PHP-8, the ZE API it used is gone now...

**Comment by m6w6** [comment]
as per https://github.com/m6w6/ext-propro/pull/5

**Comment by Jan-E** [comment]
Oops. I meant the dependent ext-raphf. For that extension an extra release would be welcome.

**Comment by m6w6** [comment]
Hmmmm, why? Seriously curious 🤷

**Comment by Jan-E** [comment]
Maybe just to trigger a PHP 8 build of the DLL's. Unless they are automatically added in the mass rebuild, announced by @cmb69

**Comment by Jan-E** [comment]
BTW: I dropped PHP_HTTP_HAVE_EXT_PROPRO in config.w32: https://github.com/m6w6/ext-http/commit/ed4c349227aaeb0a850ac641dfde43f54a04d504

**Comment by m6w6** [comment]
Yep, I saw, thanks a lot!

**Comment by cmb69** [comment]
@Jan-E, currently, no PHP 8.0 builds are done anyway. The mass rebuild is supposed to rebuild everything on https://windows.php.net/downloads/pecl/releases/ (always latest releases).

**Comment by Jan-E** [comment]
OK. With respect to ext-http 4.0 see https://phpdev.toolsforresearch.com/php-8.0.0-nts-Win32-vs16-x64.htm

**Comment by m6w6** [comment]
Bear with me, but I looked through most of extensions I noticed I kind of maintain or have to look at:

- oauth: why master and not 2.0.7?
- geoip: this is dead in PHP-8 isn't it?
- apfd & json_post: doh, no ext version in phpinfo!

Sidenote: xmlrpc? 😁

**Comment by cmb69** [comment]
I'll gladly transfer xmlrpc lead maintainership to you. :p

**Comment by Jan-E** [comment]
I always build from git head. For instance xmlrpc is built from https://github.com/php/pecl-networking-xmlrpc/commits/master

geoip does not look to be dead:
```
=====================================================================
Number of tests :   17                17
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    1 (  5.9%) (  5.9%)
Tests passed    :   16 ( 94.1%) ( 94.1%)
---------------------------------------------------------------------
Time taken      :    2 seconds
=====================================================================

=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
Checking Country (Free) DB availability [N:\php-sdk\php80dev\ext\geoip\tests\001.phpt]
=====================================================================
```

**Comment by Jan-E** [comment]
@remicollet added the arginfo to geoip: https://svn.php.net/viewvc?view=revision&revision=351082

**Comment by cmb69** [comment]
> propro is dead, though, for PHP-8, the ZE API it used is gone now...

That appears to be an issue, due to [configuration of the build machine](https://github.com/php/web-rmtools/blob/db1ec78b568cf3b6651ad72d261892c9dc1557c4/data/config/pecl/exts.ini#L242-L249). If I remove propro there, no further pecl_http 3 version could be built. Or wouldn't that be an issue?

**Comment by Jan-E** [comment]
propro is not needed anymore for PHP8, only raphf

**Comment by Jan-E** [comment]
So, we should try to avoid:
`| propro       | shared |
`
That can be achieved by adding `if (PHP_VERSION <= 7)` to the config.w32 of ext-propro:
```
ARG_ENABLE("propro", "for propro support", "no");

if (PHP_PROPRO == "yes" && PHP_VERSION <= 7) {
	var PHP_PROPRO_HEADERS=glob(configure_module_dirname + "/src/*.h");
	var PHP_PROPRO_SRC_ARRAY=glob(configure_module_dirname + "/src/*.c");
	var PHP_PROPRO_SOURCES="";
	for (var i=0; i<PHP_PROPRO_SRC_ARRAY.length; ++i) {
		var basename = FSO.GetFileName(PHP_PROPRO_SRC_ARRAY[i]);
		PHP_PROPRO_SOURCES = PHP_PROPRO_SOURCES + " " + basename;
	}

	//EXTENSION("propro");
	ADD_SOURCES(configure_module_dirname + "/src", PHP_PROPRO_SOURCES, "propro");
	EXTENSION("propro", "src/php_propro_api.c");
	PHP_INSTALL_HEADERS("ext/propro", "php_propro.h");
	for (var i=0; i<PHP_PROPRO_HEADERS.length; ++i) {
		var basename = FSO.GetFileName(PHP_PROPRO_HEADERS[i]);
		copy_and_subst("src/" + basename, basename, []);
		PHP_INSTALL_HEADERS(configure_module_dirname, basename);
	}
	ADD_FLAG("CFLAGS_PROPRO", "/I" + configure_module_dirname + " ");

	AC_DEFINE("HAVE_PROPRO", 1);
}
```
Shall I make this change?

**Comment by Jan-E** [comment]
I checked if this broke anything. It did not, even when building PHP 5.3.
So I made the change: https://github.com/m6w6/ext-propro/commit/1bf4a3379b530ca6c10940e9e16eca5b382342f2

**Comment by cmb69** [comment]
@Jan-E, thanks, this change certainly makes sense on it's own – why even try to build an extension with some PHP version where the build is guaranteed to fail? However, I'm not sure whether that would be sufficent for the PECL builder, and I actually found out that it is well possible to have different ext configurations for different PHP versions. [x64 snapshots](https://windows.php.net/downloads/pecl/snaps/http/4.0.0beta1/) are already available. I'm going to update the x86 tree, and also have a look how to fix libevent support.

**Comment by Jan-E** [comment]
I tried it with propro, raphf and http in the ext path. It starts with
`snapshot: forcing propro on`
but ends with
```
| pgsql              | shared |
| phar               | static |
| phpdbg_webhelper   | shared |
| pspell             | shared |
| radius             | shared |
| raphf              | shared |
```
It does not try to build propro at all. But I see that you already succeeded:
https://windows.php.net/downloads/pecl/snaps/http/4.0.0beta1/

**Comment by Jan-E** [comment]
I double-checked. After https://github.com/m6w6/ext-propro/commit/1bf4a3379b530ca6c10940e9e16eca5b382342f2 and a snapshot build the only references in the complete build environment to propro were some lines of js-code in configure.js (that do not get executed) and the 3 test-files that get added to x64/Release/php-test-pack-8.0.0.zip. Nothing in the Makefile or wherever else.

The configure command is at the top of https://phpdev.toolsforresearch.com/php-8.0.0-nts-Win32-vs16-x64.htm

So the commit to ext-propro effectively avoids build failures under PHP8 when propro is in the ext-path.

**Comment by m6w6** [comment]
So, we're awesome now?

**Comment by cmb69** [comment]
I think so.

**Comment by Jan-E** [comment]
Maybe it would be wise to make a final release of ext-propro, including the commit that prevents build failures under PHP8. If you agree, I will make a tiny change to the config.w32 of propro with a warning that the propro extension has been discontinued under PHP8. That will be later on today. ATM I am travelling by public transport between Amsterdam and Rotterdam, with a face mask.

**Comment by m6w6** [comment]
Alright. I'll add max/exclude PHP versions to the package.xml

**Comment by Jan-E** [comment]
https://github.com/m6w6/ext-propro/commit/921871c048332818704008ce7b67f8f2e32d3cf4 in the train near Gouda

**Comment by Jan-E** [comment]
@cmb69 
Is there any reason why https://windows.php.net/downloads/pecl/releases/http/3.2.4/ aren't linked on https://pecl.php.net/package/pecl_http ?

I can imagine that you do not link https://windows.php.net/downloads/pecl/releases/http/4.0.0/ yet. Any idea when that will be the case?

**Comment by cmb69** [comment]
One problem is the naming issue: the PECL package is called `pecl_http`, but it is build as `http`. I have copied the missing builds to https://windows.php.net/downloads/pecl/releases/pecl_http/ about an hour ago, but for some reason they are still not linked.

That might be related to the caching mechanism, but for some (potentially related) reason, requesting https://pecl.php.net/package/pecl_http takes a very long time to respond (at least for me). 

I'm keeping an eye on this, and will investigate further if the DLLs are not listed later today or tomorrow.

**Comment by m6w6** [comment]
> That might be related to the caching mechanism, but for some (potentially related) reason, requesting https://pecl.php.net/package/pecl_http takes a very long time to respond (at least for me).

Doesn't it do that for every package for years now? (since the PECL server mirated?)

**Comment by m6w6** [comment]
> PS: ah, I need to fix the names as well. @m6w6, could that naming mess be resolved at some point in the future? :)

As explained, it's that way because there's a PEAR HTTP package, and there's formal support in tooling and package.xml in form of "package>providesextension" vs "package>name". So, granted, it's clunky, but not a mess. :grin: 

What I personally consider a mess, is the possibility of creating mixed case package names :sob: :slightly_smiling_face:

**Comment by cmb69** [comment]
Requesting the package pages often takes quite some time, but for pecl_http it was even way longer. I shall have a look at that caching mechanism; it may not work as expected (perhaps due to the move to CDN).

Anyhow, the DLLs are now listed. \o/

The naming issue is addressed for the builds, but unfortunately not for the uploads. If it's not possible to change names, I shall have a look at this as well.

**Comment by shivammathur** [comment]
@cmb69 Looks like the DLLs for pecl_http were built using older versions of ICU than what is shipped with compatible PHP versions currently. Can pecl_http 4.0.0 and 3.2.4 be rebuilt with version of ICU matching with PHP.

**Comment by Jan-E** [comment]
Closing. If any problem still exists it has to be addressed separately.
